### ISSUE TITLE
Create new table in DB, Add crud methods and write test cases

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#104]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create new db model `AirDrop` [here](https://github.com/djeck1432/spotnet/blob/main/web_app/db/models.py) with next fields:
- user_id - ForeingKey
- created_at - DateTime  (add autopopulating by `now`)
- amount - Decimal( null=True)
- is_claimed - Boolean (default =False) 
- claimed_at - DateTime(null =True)
3.1. In `DBConnector` add new method:
- `create_empty_claim` which will have one parameter: `user_id` and will create new `airdrop` instance
3.2 Create new `AirDropDBConnector` [here](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py) which is inherited from `DBConnector` and add next methods:
- `save_claim_data` which will save info about `claim`: `amount`, `is_claime`=True, and `claimed_at` = datetime.now()
- `get_all_unclaimed` - which will return all records, where `is_claimed` = False
4. Update this method [open_position](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L320) with creating new AirDrop instance (user this method `create_empty_claim`). `user_id` you can fetch from `position.user_id` 
5. Write test cases (positive and negative scenarios) for new class `AirDropDBConnector` in `tests` folder
6. Update `DBConnector` test cases for new method `create_empty_claim` write positive and negative scenarios.

When you create PR, make sure you don't have any pylint issues and running tests didn't fail

**Comment by ikemHood** [comment]
Hey @djeck1432, Can I work on this, please?
I Like Orange

I will create the Airdrop model with the values provided

ETA: 4hrs

**Comment by BrunoAmbricca** [comment]
I’d love to work on this task.

**Comment by tosoham** [comment]
I am a returning contributor here. I would be glad to tackle this issue as I have already worked with the db adding new field to Position.

**Comment by Jemiiah** [comment]
Hey @djeck1432 can I work on this issue

**Comment by BrunoAmbricca** [comment]
I like orange. I would like to contribute to this project doing this task. 

I would follow the guideline in the repo for fork, clone & pull request. I would clone the project on my local machine. I would study the code base to understand how AirDrop interacts with it. After the implementation I would test to make sure everything works as expected

**Comment by binayak9932** [comment]
Let me try this one!I am a returning contributer i am sure i can carry this out.I like oranges

**Comment by ShantelPeters** [comment]
Hi @djeck1432 pleass can I be assigned to this issue. This would be my first time contributing to this ecosystem
