### ISSUE TITLE
Create endpoint for fetching all available airdrops by contract_address

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#105]
1. Read [guidelines](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5).
2. Create new file: `airdrop.py` in [contract_tools](https://github.com/djeck1432/spotnet/tree/main/web_app/contract_tools)
3. Create new class in new file `airdrop.py` `ZkLendAirdrop`  which will have next methods
- `__init__`
- `get_contract_airdrop(contract_id)` (call to endpoint to fetch all available airdrops) feel free to use this [class](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/api_request.py#L8) for sending requests
[url example](https://app.zklend.com/api/reward/all/0x020281104e6cb5884dabcdf3be376cf4ff7b680741a7bb20e5e07c26cd4870af)
- `_validate response` ( which will validate data and return it in better format, remove unnecessary info, we want to see next fields only: 
    - `amount`
    - `proof`
    - `is_claimed`
    - `recipient`
)
4. Create Pydantic model, result of `_validate_response` 
- in this [folder](https://github.com/djeck1432/spotnet/tree/main/web_app/api/serializers), create `airdrop.py` 
5. Add test cases for `ZkLendAirdrop` positive and negative for each method

When you create PR, make sure you don't have any pylint issues and running tests didn't fail

**Comment by PoulavBhowmick03** [comment]
I'd love to give this a go.
I would love to work on this!

**Comment by binayak9932** [comment]
I'd like to take this issueI am a python Devand  I am a returning contributor here  i am sure i can carry this out.I like oranges

**Comment by Jemiiah** [comment]
i

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue @djeck1432 ..
I like oranges

**Comment by BrunoAmbricca** [comment]
I like orange. I would like to contribute to this project by doing this task.

I would follow the guideline in the repo for fork, clone & pull request. I would clone the project on my local machine. I would study the code base to understand how  ZkLendAirdrop should iteract with it. After the implementation I would test to make sure everything works as expected

**Comment by Jemiiah** [comment]
Can i take this?@djeck1432

I like oranges

- First I will  create the Pydantic model AirdropData to define the data structure
- Then Create the ZkLendAirdrop class with:

-- _init_ to set up base URL
get_contract_airdrop to fetch data
-- _validate_response to clean and validate response


Add comprehensive tests covering:
- Successful airdrop fetching
- Invalid response handling
- Network error handling
