### ISSUE TITLE
Add celery[redis] package to the project

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#106]
1. Read [guidelines](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5).
2. Set up `celery` for the project [package](https://docs.celeryq.dev/en/main/getting-started/introduction.html)
3. Update `docker-compose.yaml` and `docker-compose.dev.yaml` with `redis` for `celery`  
4. Create simple `task` function to verify that all works as expected
5. Update `entrypoint.sh` file for start up `celery` workers 
6. Update README.md about celery and how to run/stop/purge

This task for old contributors not for newcomer

**Comment by akintewe** [comment]
hello please can i be assigned

**Comment by Jemiiah** [comment]
can iw work on this 
I like Orange

**Comment by PoulavBhowmick03** [comment]
I like orange

**Comment by tosoham** [comment]
I am a returning contributor here. Can I handle this task? I like orange

**Comment by iamnovichek** [comment]
Greetings. I have extensive experience in crypto development and this task will be completed quickly and efficiently. Can I be assigned? I like orange.

**Comment by djeck1432** [comment]
Again, complex tasks could be done by someone, who is already contributed and showed good result. For server related tasks, if you have done more than 2-3 medium/complex  tasks at all.
