### ISSUE TITLE
Create test cases for PositionDBConnector

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#109]
1. Read [guidelines](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5).
2. Add positive and negative test cases for class methods [PositionDBConnector](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L160)
3. Use please mock connection to db from [confest.py](https://github.com/djeck1432/spotnet/blob/main/web_app/tests/conftest.py)
4. Make sure you have run successfully `pylint` command without any issues 
`pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301`

**Comment by Jemiiah** [comment]
Can i work I this @djeck1432
