### ISSUE TITLE
Save current price into `Position.start_price` 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#114]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Use this method to fetch current price for `position token` by symbol `DashboardMixin.get_current_prices` [here](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/mixins/dashboard.py#L13)
4. Add this token current price to `start_price` by selected token

**Comment by UzNaZ** [comment]
Hello, I am backend developer with appropriate database knowledge. I would like to apply for this task, and since i love apple i think i will be a nice choice for it. Looking forward to hearing from you.
