### ISSUE TITLE
FE Project Setup and Code Quality Improvements

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#115]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Replace the browser's built-in alert() and use the libraries Sonner or React Toastify for alert messages.
3. Set up ESLint and Prettier to enforce code quality and style consistency across the project.
4. Review and rename folders in the project to follow a consistent naming convention. Update any relevant import paths in the codebase to reflect the new folder names.
5. Ensure all instances of alert() are removed and replaced with the chosen library's notification methods.
6. Ensure that all folder names adhere to the established style throughout the project.
7. Configure Absolute Imports

**Comment by AndriiBogomolov** [comment]
Hi, I love apple, I contributed to this project a lot of times, would like to take this task, as far as I know code base very well
