### ISSUE TITLE
Implement Form Page Enhancements: Balance Cards, Background & Styling Updates, and Alert Positioning

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#120]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add balance cards to Form page according to figma with functionality for interacting with the server to receive data.
3. Add background styles to Form page: stars and background gradient, according to figma.
4. Add styles to radio buttons "Select Token" and "Select Multiplier" at the Form page, according to figma.
5. Move alert message "Please fill the form" above radio buttons "Select Token" according to figma.
6. Text me to telegram, I will give you access to Figma if you need it (my telegram handler: djeck_vorobey1)

**Comment by BrunoAmbricca** [comment]
Hello. I like 🍌. Also I would like to contribute to this project and do this issue. Im a software engineer with 4+ years of fullstack experience.

**Comment by ikemHood** [comment]
Hello @djeck1432 ,

I would design the balance card following the figma design, I like 🍌.
