### ISSUE TITLE
Update Header Layout and Styles: Relocate ‘Log out’ Button, Enhance Button States, and Color Changes for Navigation

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#121]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Change position of "Log out" button in header, after connecting to the wallet the button should appear at the right side of the header but left side of the wallet id banner.  
3. Please also change "Log out" button's styles according to the figma.
4. Add color change on selected and pressed states for "Home" and "Dashboard".
5. Make sure the "Log out" button has right place and styles, also "Home" and "Dashboard" change color when state changes.
6. Text me to telegram, I will give you access to Figma if you need it (my tg handler: djeck_vorobey1)

**Comment by raizo07** [comment]
Can I work on this?

**Comment by djeck1432** [comment]
Finish your current task and then reapply again

**Comment by PoulavBhowmick03** [comment]
Mind if I try this one?

**Comment by PoulavBhowmick03** [comment]
I'd like to take it up
I like 🍌
I'm Poulav Bhowmick, a Starknet Wolf. I am a returning contributor. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

Approach

I would go through the code and figure out the changes. I will DM for the figma link for a better reference 

Eta - 2 days

**Comment by BrunoAmbricca** [comment]
Hello. I like 🍌. Also I would like to contribute to this project and do this issue. Im a software engineer with 4+ years of fullstack experience.

**Comment by Mystic-Nayy** [comment]
Can I be assigned please?
I like 🍌
ETA -24hrs
