### ISSUE TITLE
Refactor API Integration and Business Logic: Replace Fetch with Axios, Relocate Starknet Logic, and Verify API Functionality

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#122]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Remove all instances of the fetch method in the project and use base instance of Axios instead.
3. Reorganize Business Logic: move all business logic related to Starknet from the Utils folder to the new Services folder.
4. Ensure that all API endpoints are working correctly via the Axios instance.
5. Ensure that all Axios calls return the expected results and that the business logic correctly interacts with Starknet.

**Comment by OWK50GA** [comment]
Hi, I'm a Frontend Web Developer with experience with starknet integration. I'll like to work on this issue.

The steps are clearly stated in the description, and I will ensure to follow them.

**Comment by djeck1432** [comment]
@OWK50GA Read guideline

**Comment by PoulavBhowmick03** [comment]
Can I tackle this one?

**Comment by PoulavBhowmick03** [comment]
I'd like to take it up
I love banana
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

### Approach

**Comment by OWK50GA** [comment]
Can I handle this task?
Hi, I'm a Frontend Web Developer with experience with starknet integration. I'll like to work on this issue. I like 🍌

**Here's how I plan to carry this out:**

I will go through the project, spotting all the places the fetch API is used and replace the fetch API logic with equivalent logic using axios, while ensuring the API calls returns the correct things and interacts seamlessly with Starknet. I will also test edge cases to ensure there is no break in the UI and ensure type safety in each and every case, to avoid errors. 
Next, I will look through the project and get the logic related to Starknet from the utils folder to the Services folder.

**Comment by ryzen-xp** [comment]
Would love to tackle this!

**Comment by OWK50GA** [comment]
@djeck1432
The docker isn't starting and now my PC crashed somehow. It's better to assign someone else

**Comment by GideonBature** [comment]
I like 🍌.

I am a Software Engineer with experience in JavaScript and Python and recently in Cairo. 

I have worked on something similar to this, which has to do with refactoring, here is a link to it: https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/issues/78

I will go through the code to identify every where an instance of fetch method is used, change it to instance of Axios. Afterwards, test it to be sure it's working as it's suppose to.

Next, will then move all the business logic code that is related to Starknet from the utils folder to the services folder. Will make sure nothing is broken, fix the imports and exports where necessary and finally test it to make sure the Axios calls returns the expected results and business logic is interacting with Starknet correctly. Thank you!

**Comment by ikemHood** [comment]
Can I take this, I like 🍌 

I am a fullstack software developer with 3+ years of experience.

I will install axios if not install yet and create an axios utils that instantiated axios,
Then, I'd replace all fetch with axios and ensure the data are processed correctly i.e `remove res json()` in favor of `res.data`
Then, I'd create a service folder and mover the starknet logics into it making sure that all import are synced and all operations works,
Test the new changes to ensure everything works as expected.

ETA: 24hrs

**Comment by MrRoudyk** [comment]
May I pick this up?

**Comment by wheval** [comment]
Hi, I'd love to work on this! I'm an experienced Frontend Developer with experience working with axios and API integrations and I like 🍌.

Here is how I would tackle this:
I will go through the project carefully, to identify all the places the fetch API is used and how the fetched data is consumed. Then i would replace the fetch API with the axios methods, while ensuring the API calls returns the data correctly by adding type annotations and also prevent repetitive logic. I will also test the UI to ensure that the data displays correctly, where it is needed.
Then, I will look through the project for the business logic related to Starknet and move them from the utils folder to the services folder. I would ensure all the endpoints works and interacts with starknet correctly. I would also write good documentation comment for how the code works to make it easier for others. Thanks.

ETA is 2 days. I can start working immediately

**Comment by vitaliypopel** [comment]
Hey! I will replace fetch with axios as soon as possible, I had experience with it, btw I like 🍌.

**Comment by djeck1432** [comment]
> @djeck1432 The docker isn't starting and now my PC crashed somehow. It's better to assign someone else

yeah, I'm working on it, sorry for inconvience

**Comment by OWK50GA** [comment]
My PC is up again, so when you're done working on it, I'm still available

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by djeck1432** [comment]
@OWK50GA I fixed docker issue, if you want to continue, let me know

**Comment by OWK50GA** [comment]
> @OWK50GA I fixed docker issue, if you want to continue, let me know

@djeck1432 I want to continue. I'll be done by the end of today
