### ISSUE TITLE
Set up Poetry for project

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#123]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Install poetry
3. Update [Dockerfile](https://github.com/djeck1432/spotnet/blob/main/Dockerfile)
4. Remove [requirements.txt](https://github.com/CarmineOptions/derisk-research/blob/master/requirements.txt)

**Comment by vitaliypopel** [comment]
I have a great background with Python and I already done more than 2 tasks in your project, so I can help you with replacing pip with poetry. And also I will improve Dockerfile with poetry. Btw I love banana

**Comment by ryzen-xp** [comment]
Could I take a shot at this?

**Comment by Mystic-Nayy** [comment]
@djeck1432 can I please be assign to work on this?
I love 🍌 
ETA -24hrs
