### ISSUE TITLE
Add new workflow for running FE tests

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#132]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create new workflow for running FE tests
3. Change all flow to run it automatically if any pushes or creating PR

**Comment by iamnovichek** [comment]
Hi! May I be assigned to this task? Since I'm an experienced developer and I've already resolved several tasks, It would be easy for me and I'd send a PR in several hours.I like bananas
