### ISSUE TITLE
Create function to claim airdrop

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#137]
1. Read [guidelines](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5).
2. Create new folder in `web_app` with name `tasks`. In this folder create `claim_airdrops.py`
3. Fetch using all aidrops [AirDropDBConnector.get_all_unclaimed()](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L396)
4. Create fucntion `claim_aidrops` which will using [StarknetClient](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/blockchain_call.py#L31) to `claim` aidrop
5. If `claim` was successful please, update `airdrop` instance using [AirDropDBConnector.save_claim_data()](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L396)
6. Link to [contract](https://starkscan.co/contract/0x03766ad221286f536405ab3e6690ab6ec6da3e32c14e756660ff7b854e0fab10#read-write-contract-sub-write) where you need to use `claim` method.
7. For fetching `proof` for `claim` method, use [ZkLendAirdrop.get_contract_airdrop](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/airdrop.py#L24C15-L24C35)
9. Apply only if you have already worked with starknet scanner and starknet_py

P.S. `AirDropDBConnector.get_all_unclaimed()` will return list of `airdrop` instances, to get contract_address you should do `airdrop.user.contract_address`. `Contract_address` in another table `User`

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by Akshola00** [comment]
hi 
can i work on this

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by Ugo-X** [comment]
Would love to tackle this!

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by anonfedora** [comment]
Hi, I'm a fullstack Blockchain developer, and i can handle the issue efficiently. ETA: 1 day

**Comment by Yunusabdul38** [comment]
Am a blockchain developer, I'd love to work on this!

**Comment by mimisavage** [comment]
Can I resolve this ?

**Comment by aniruddhaaps** [comment]
I'm a python dev, a new-comer here. I want to take up the issue and solve it.

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by godekina** [comment]
I am a Python developer who has contributed to DeFi.  I like 🍒.
This is how I intend to approach the task:
1. I will fetch the all airdrops returned from the function get_all_unclaimed.
2. Then I will create fucntion claim_aidrops which will using StarknetClient to claim aidrop
3. I will write logic to update airdrop instance using AirDropDBConnector.save_claim_data() if the claim was successful

I will like to take on this task, this will be my first time of contributing to this project.

**Comment by aniruddhaaps** [comment]
To complete this, I’ll create a claim_airdrops.py script within tasks that fetches unclaimed airdrops with AirDropDBConnector.get_all_unclaimed(), claims each one using StarknetClient, and updates the database upon successful claims. I’ll also retrieve proofs via ZkLendAirdrop.get_contract_airdrop to pass into the claim method.

**Comment by caxtonacollins** [comment]
please i will love to work on this issue. I am ready to work

**Comment by caxtonacollins** [comment]
please i will love to be assigned to this issue; this will be my first time contributing. thank you. I like 🍒. and am ready to work

**Comment by mimisavage** [comment]
Can I be assigned to this ?
This will be my first time contributing 
And I promise to put in my very best

**Comment by djeck1432** [comment]
@mimisavage PLEASE, READ GUIDELINE first

**Comment by djeck1432** [comment]
@godekina left 6 hours, prepare your draft RP
