### ISSUE TITLE
Create script to populate with fake data db.

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#138]
1. Read [guidelines](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5).
2. For all tables, create 10 different instances with different values per model. All models are [here](https://github.com/djeck1432/spotnet/blob/main/web_app/db/models.py)
3. Create script to connect to db and add fake data. 
4. Update `Readme.md` how to do that.

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by Gerson2102** [comment]
I like 🍒, can I work on it?

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by od-hunter** [comment]
Can I work on this, I like 🍒

I'm a first time contributor

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by martinvibes** [comment]
can i work on this :)

**Comment by Gerson2102** [comment]
### Hey! I'm Gerson and I like 🍒. 👋

Member of **Dojo Coding**. I have contributed before to other Python projects like:

- `giza-agents`
- `derisk-search`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by mimisavage** [comment]
I'd love to resolve this

**Comment by josephchimebuka** [comment]
Can I try solving this issue?

**Comment by mimisavage** [comment]
Can I work on this ?

**Comment by mimisavage** [comment]
Let me solve this

**Comment by ikemHood** [comment]
Hey @djeck1432, can I jump on this,
I like 🍒

For each collection in the model, I would write some dummy data,
Then write a script that connects to the database and write the dummy data

Final will write a readme to describe the process 

ETA: 24hrs

**Comment by godekina** [comment]
I am a python developer and I have contributed to DeFi, I like 🍒.
1. I will write a python script that creates 10 different model instances
2. I will also include a script that connects to the database and inserts that fake data into it. 
I'd love to work on this issue, this will be my first time of contributing to this project.

**Comment by 0xdevcollins** [comment]
Could I grab this task?

**Comment by aniruddhaaps** [comment]
To solve this, I’ll create a script to connect to the database, generating 10 distinct entries per model (User, Position, AirDrop, and TelegramUser) with diverse values. I’ll also update README.md with step-by-step instructions for running the script.

**Comment by caxtonacollins** [comment]
please i will love to be assigned to this issue; this will be my first time contributing. thank you

**Comment by caxtonacollins** [comment]
please i will love to be assigned to this issue; this will be my first time contributing. thank you. I like 🍒

**Comment by baitcode** [comment]
Experience: https://www.linkedin.com/in/batiyiv/
Plan: 
- Study data schema
- Use https://github.com/json-schema-faker/json-schema-faker to create schema, probably write couple of plugins to generate specific data types.

**Comment by mimisavage** [comment]
Can I handle this ?

**Comment by djeck1432** [comment]
@caxtonacollins Left 6 hours, please prepare your draft PR
