### ISSUE TITLE
 Display on FE TVL and Users

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#139]
1. Read [guidelines](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5).
2. This method http://localhost:8000/api/get_stats should return you next data: 
```
{
  "total_opened_amount": "1000.0",
  "unique_users": 0
}
```
3. Make it dynamic and fetch data from endpoint and display in [fronted code](https://github.com/djeck1432/spotnet/blob/main/frontend/src/pages/spotnet/information/Informaion.jsx#L16)
4. On Fronted it should be `TVL`=`total_opened_amount`  and `Users` = `unique_users` which you can fetch from Backend endpoint

**Comment by mimisavage** [comment]
Can I be assigned to this ?

**Comment by djeck1432** [comment]
@mimisavage read guideline and feel free to apply to another issue

**Comment by josephchimebuka** [comment]
I’d like to work on this.

**Comment by aniruddhaaps** [comment]
I'm a javascript dev, a new-comer here. I want to take up the issue and solve it.

**Comment by mimisavage** [comment]
Can I resolve this ?

**Comment by aniruddhaaps** [comment]
To implement this, I’ll update the frontend to dynamically display "TVL" and "Users" by fetching total_opened_amount and unique_users from the /api/get_stats endpoints which will render the response accordingly and accurately.

**Comment by KevinLatino** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/

How I plan on tackling this issue

To address this issue effectively, here's my plan:

Understand Endpoint and Data Structure: I’ll start by confirming the exact structure of the data returned from the endpoint at http://localhost:8000/api/get_stats. This will ensure I correctly map the values of total_opened_amount to TVL and unique_users to Users on the frontend.

Create API Integration: I'll use fetch or axios to call the get_stats endpoint within the frontend code. This will involve setting up a service or utility function to handle the data fetching, including error handling and loading states, which is crucial for a responsive UI.

Map Data to UI Elements: On the frontend, I'll display total_opened_amount and unique_users in a user-friendly format. For example, TVL will show total_opened_amount, and Users will show unique_users. I’ll ensure these elements update in real time by using React’s useEffect with dependency tracking, allowing data to refresh when needed.

Testing and Edge Cases: I will test the implementation thoroughly, including scenarios where the data might not load (e.g., server issues, network latency). Additionally, I'll confirm that TVL correctly displays as a float (e.g., “1000.0”) and Users as an integer, meeting the provided guidelines.

@djeck1432  I would love to contribute to this amazing project! I hope you can give me the opportunity!

**Comment by mimisavage** [comment]
I need to fetch data from the /api/ get_ stats endpoint, which returns
JSON data containing total_opened_amount and unique_ _users. I'll then display this data on the frontend, mapping total_opened_ _amount to TVL and unique users to Users.

I'll use JavaScript with the Fetch API to make a GET request to the endpoint. For simplicity, I'll assume a basic HTML structure and use Vanilla JavaScript.

**Comment by caxtonacollins** [comment]
May I pick this up? I like 🍒

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by martinvibes** [comment]
i would hanndke this task in the following way` i like 🍒`
- Set Up Backend Endpoint: Ensure /api/get_stats returns total_opened_amount and unique_users values.

- Fetch Data on Frontend: Create a function to request data from the /api/get_stats endpoint.

- Display Data on Frontend: Map total_opened_amount to "TVL" and unique_users to "Users," then display these on the frontend.

- Test and Verify: Ensure values update dynamically based on the backend response.

**Comment by mimisavage** [comment]
Can I be assigned?
