### ISSUE TITLE
Add test cases for Airdrop class

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#141]
1. Read [guidelines](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5).
2. Create new file `test_zklend_airdrop.py` in [tests folder](https://github.com/djeck1432/spotnet/tree/main/web_app/tests)
3. Created positive and negative test cases for this [ZkLendAirdrop class](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/airdrop.py#L9)

**Comment by od-hunter** [comment]
Can I work on this

**Comment by djeck1432** [comment]
Nope:
1. Tasks for new comers
2. you didn't read guidelines

**Comment by martinvibes** [comment]
i'm new sir @djeck1432 i haven't contributed yet

**Comment by josephchimebuka** [comment]
Can I tackle this one?

**Comment by djeck1432** [comment]
> i'm new sir @djeck1432 i haven't contributed yet
@martinvibes even though, you didn't do 1. read guideline

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by mimisavage** [comment]
Can I work on this ?

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by Ugo-X** [comment]
I'd like to handle this task.

**Comment by Yunusabdul38** [comment]
I’d like to work on this.

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by od-hunter** [comment]
Can I work on this, I like 🍒

**Comment by anonfedora** [comment]
hi, i'm a fullstack blockchain developer and i can handle the issue efficiently. ETA: 8hours

**Comment by mimisavage** [comment]
Would love to tackle this !

**Comment by binayak9932** [comment]
i worked on this  project and i am familiar with its codespace i can think i can do this  also I like 🍒 very much 😊

**Comment by aniruddhaaps** [comment]
I'm a javascript dev, a new-comer here. I want to take up the issue and solve it.

**Comment by mimisavage** [comment]
Would love to tackle this !

**Comment by suhas-sensei** [comment]
I like 🍒. I'll implement comprehensive test suite focusing on boundary conditions and time-sensitive edge cases for ZkLendAirdrop class, aiming to deliver by Nov 2nd. Have experience writing Pytest fixtures/mocks for blockchain protocols and DeFi airdrop mechanisms.

**Comment by mimisavage** [comment]
Would love to tackle this

**Comment by aniruddhaaps** [comment]
To solve this, I shall write test_zklend_airdrop.py with some positive and negative test cases on the ZkLendAirdrop class. I focus on get_contract_airdrop and _validate_response to acquire proper API responses along with proper validation behavior.

**Comment by mimisavage** [comment]
Let me resolve this

**Comment by 0xdevcollins** [comment]
Is this issue still available?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js, TypeScript, and Python. I’ve made over 31 contributions to over 12 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

To create a new test cases for the `ZkLendAirdrop class`, I will create a `test_zklend_airdrop.py` file to include positive and negative test cases. Positive cases will mock valid responses from the `REWARD_API_ENDPOINT` to verify correct data fetching and validation, ensuring that `AirdropResponseModel` and `AirdropItem` instances are properly structured. Negative cases will test invalid `contract_id` inputs and malformed API responses, confirming that  `_validate_response` handles errors gracefully.  I will also ensure all GitHub checks pass for robustness. My ETA is 48hrs from when the task is assigned to me. I like 🍒. Thanks.
