### ISSUE TITLE
Add notebook from calculating heath-ratio-level from on-chain

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#142]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. You will need to use [`converter`](https://www.stark-utils.xyz/converter), [`StarkScan`](https://starkscan.co/contract/0x04c0a5193d58f74fbace4b74dcf65481e734ed1714121bdc571da345540efa05#events)
4. Create notebook with your comment and Ideas how to implement it
5. What you need to know:
 - Collect only `Borrowing` and `Deposit` events
 - Zklend smart contract `0x04c0a5193d58f74fbace4b74dcf65481e734ed1714121bdc571da345540efa05`
 - In result you should have `raw_amount` `face_amount` from `Borrowing`
 - In result you should have `face_amount` from `Deposit`

**Comment by NueloSE** [comment]
Could I be assigned to this? ETA <=3days

**Comment by djeck1432** [comment]
@NueloSE 3 Days are too much

**Comment by mimisavage** [comment]
I'd love to work on this

**Comment by djeck1432** [comment]
@mimisavage please, stop spamming, wrote you 3 times, READ GUIDELINE

**Comment by mimisavage** [comment]
Sorry about that .. must be network issues

**Comment by Jemiiah** [comment]
@djeck1432 pls can I be assign I like 🍒 ETA: 24 hours

**Comment by Jemiiah** [comment]
@djeck1432 ols can I be assign I like 🍒 ETA: 24 hours

**Comment by BrunoAmbricca** [comment]
Hello hello. I like 🍒. I would like to do this issue

**Comment by djeck1432** [comment]
@BrunoAmbricca @Jemiiah This task is not easy, if you have never used startkscan, at least I can't see it in your application

**Comment by Jemiiah** [comment]
I have used starkscan before 🙂

**Comment by Kostya-59benz** [comment]
Want to work on this issue.

**Comment by Mystic-Nayy** [comment]
@djeck1432 can I work on this?
I’ve used starkscan and I like 🍒
ETA -24hrs

**Comment by jaykayudo** [comment]
I'd love to work on this!
I like 🍒

**Comment by djeck1432** [comment]
@Mystic-Nayy Please, fix in Derisk Merge Conflict, waiting to merge it and can't you are blocking us
