### ISSUE TITLE
Disable unused wallets on Frontend

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#146]
1. Read [guidelines](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5).
2. At the moment, we have a batch of wallets, which we don't want to support:
<img width="370" alt="Screenshot 2024-10-30 at 9 14 33" src="https://github.com/user-attachments/assets/4abfd918-b4e2-4266-93ad-f20608fa1dd6">
3. We want to have only `argent X` and `bravos` 
4. Make this changes on Frontend to restrict choices for available wallets. Wallet code is [here](https://github.com/djeck1432/spotnet/blob/main/frontend/src/utils/wallet.js)

**Comment by SailorJhay** [comment]
Hey @djeck1432 , I am a frontend developer with 2yrs of expirence.
i would love to work on this, I like 🍒.

**Comment by djeck1432** [comment]
@SailorJhay did you apply via OnlyDust?

**Comment by SailorJhay** [comment]
Hey @djeck1432 , I am a frontend developer with 2yrs of expirence.
i would love to work on this, I like 🍒.
First time contributor on ODHAck and spotnet

**Comment by SailorJhay** [comment]
> @SailorJhay did you apply via OnlyDust?
just did.

**Comment by djeck1432** [comment]
@SailorJhay You have 24 hours to make draft PR.

**Comment by SailorJhay** [comment]
will do now.

thank you
