### ISSUE TITLE
Add rebalancing user position 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#152]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. After claiming aidrop and user will have rewards on its contract, send partially reward back to zkLend contract as a collateral to rebalance its portfolio.
3. 5% of collateral -> our Treasury [ it could be more than 5% than rest of it, we can send to user back]
4. rest of it to user contract for rebalancing 
5. Add test cases to test it.
This task is quite complex and should be done as soon as possible.
you can apply if you have at least 1 year experience in Cairo.

**Comment by tensojka** [comment]
I like 🍒.

And can take on this task

**Comment by djeck1432** [comment]
Done
