### ISSUE TITLE
Optimize Component-Backend Communication and Styling:  Refactor CSS for Improved Performance

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#153]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Optimize CSS files by dividing them into smaller, more focused files, grouping styles by component or feature to improve maintainability and load performance.
3. Ensure that the application maintains its expected performance and responsiveness following the optimizations.

**Comment by ikemHood** [comment]
Can I get on this @djeck1432 ,
 "I like 🍒
ETA: 24hrs

**Comment by SailorJhay** [comment]
Can I contribute to this one?
I like 🍒

**Comment by AndriiBogomolov** [comment]
Hi, I like 🍒. Let me do it. Thank you
