### ISSUE TITLE
Make adaptive Main page  

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#154]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Make adaptive design for `phones` and `tablet` for main page
3. This task only for project contributors not for new comers

**Comment by od-hunter** [comment]
Can I be assigned this please? I like 🍒

**Comment by Jemiiah** [comment]
@djeck1432 i wld love to work on this issue I like 🍒

**Comment by djeck1432** [comment]
Please, let me know your experience as well

**Comment by Benjtalkshow** [comment]
can i work on this issue? I like 🍒

**Comment by KevinLatino** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/

Also as a fun fact, i like 🍒

To resolve the adaptive design task for phones and tablets on the main page, I will implement CSS media queries to create a responsive layout that adjusts to different screen sizes. I will ensure all elements are displayed correctly and optimize the user experience across devices. Additionally, I will test the design on various devices to verify responsiveness.

**Comment by mimisavage** [comment]
Can I be assigned this ?
I like 🍒
