### ISSUE TITLE
Make adaptive design for `dashboard` page

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#155]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Make adaptive design for `phone` and `tablet` for `dashboard` page
3. This task only for project contributors not for new comers

**Comment by ShantelPeters** [comment]
Hi

**Comment by Benjtalkshow** [comment]
can i work on this issue? I like 🍒

**Comment by PoulavBhowmick03** [comment]
Can I start working on this?
I like 🍒
I have contributed to this project previously and I can add adaptive design for phone and tablet in form page

**Comment by PoulavBhowmick03** [comment]
Can I start working on this?
I like 🍒
I have contributed to this project previously and I can add adaptive design for phone and tablet in dashboard page

**Comment by mimisavage** [comment]
Can I be assigned this please?
I like 🍒
