### ISSUE TITLE
Make adaptive design for Form page

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#156]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Make adaptive design for `phone` and `tablet` for `form` page
3. This task only for project contributors not for new comers

**Comment by 0xdevcollins** [comment]
I like 🍒

Can I tak this?

**Comment by Benjtalkshow** [comment]
can i work on this issue? I like 🍒

**Comment by PoulavBhowmick03** [comment]
Can I start working on this?
I like 🍒
I have contributed to this project previously and I can add adaptive design for phone and tablet in form page

**Comment by mimisavage** [comment]
Please , I would love to work on this issue 
I like 🍒

**Comment by djeck1432** [comment]
@Benjtalkshow Any updates? I can't see any draft PR

**Comment by Benjtalkshow** [comment]
> @Benjtalkshow Any updates? I can't see any draft PR

yes. Will make a draft PR now

**Comment by djeck1432** [comment]
@Benjtalkshow you have 30 mins to create draft PR, otherwise you will be unassigned
