### ISSUE TITLE
Add new Congratulation page from figma

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#157]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create new page `congratulation` from figma
3. Redirect to this page, once `Postion is opened` 
4. Text me in DM [telegram] to get access to figma djeck_vorobey1

**Comment by Jemiiah** [comment]
@djeck1432 I would love to work on this issue I like 🍒

**Comment by od-hunter** [comment]
I like 🍒
Can I be assigned this please

**Comment by Benjtalkshow** [comment]
can i work on this issue? I like 🍒

**Comment by 0xdevcollins** [comment]
can I work on this? I like 🍒

**Comment by ShantelPeters** [comment]
I am a blockchain developer with strong background in JavaScript, typescript, python etc.
Please can I be assigned to this issue 
I love 🍒
And I’m ready to work

**Comment by djeck1432** [comment]
@Jemiiah text me in DM with your email, I will share with you figma access

**Comment by Botdavid** [comment]
Could I be assigned to this?

**Comment by Jemiiah** [comment]
> @Jemiiah text me in DM with your email, I will share with you figma access

Aiii ser

**Comment by mimisavage** [comment]
Can I work on this issue ?
I like 🍒

**Comment by djeck1432** [comment]
@Jemiiah Hi, in a few hours waiting for draft PR, otherwise you will be unassigned

**Comment by djeck1432** [comment]
@Jemiiah Any updates? I can't see any draft PR

**Comment by djeck1432** [comment]
@Jemiiah You have 30 mins to create draft PR, otherwise you will be unassigned

**Comment by Jemiiah** [comment]
alright ser @djeck1432

**Comment by Jemiiah** [comment]
Creating a PR as we speak
