### ISSUE TITLE
Implement TanStack Query Hooks

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#160]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Refactor all communication between components and the backend to utilize custom hooks using the TanStack Query library for managing server state and data fetching within these hooks. 
3. Ensure that all components function correctly with the new custom hooks and that data is being fetched properly.
4. Ensure that the application maintains its expected performance and responsiveness following the optimizations.

**Comment by AndriiBogomolov** [comment]
Hi, I like 🍒. I can perform the task. Please let me do it. Thank you.
