### ISSUE TITLE
Rework dashboard page

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#168]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Rework appropriate to design `dashboard` `Collateral and Earnings part`
3. Set as `start sum` and `current sum`  as 0 
4. Pay attention, is `start sum` is greater than `current sum` then `current sum` should be read color, if 
5. `start_sum` is less than `current sum` it should be green
Text me in telegram to get access to figma  `djeck_vorobey1`

**Comment by raizo07** [comment]
Can I work on this

**Comment by Josh-121** [comment]
May I pick this up?

**Comment by Josh-121** [comment]
Can I take this? I like 🍒.

**Comment by mimisavage** [comment]
I would love to take this up. I like 🍒

**Comment by omsant02** [comment]
I'd like to handle this task. I like 🍒

i am planning to resolve this issue by putting some control flow in the logic

**Comment by Kaminar-i** [comment]
Is there an opportunity for me to work on this issue?, I like 🍒.

**Comment by ooochoche** [comment]
I have read through the guidelines and also the rework description, and I can resolve this, @djeck1432 🍒

**Comment by KevinLatino** [comment]
I like 🍒

To implement the logic for the Collateral and Earnings section, set both `startSum` and `currentSum` to an initial value of 0. Then, create a conditional statement to check whether `currentSum` is greater or less than `startSum`. If `currentSum` is greater than `startSum`, display the `currentSum` in green; if it’s less, display it in red. This color logic will help visually represent increases and decreases in earnings or collateral on the dashboard.
