### ISSUE TITLE
Rework Form with slider 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#169]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Rework appropriate to design `form` with adding slider
3. Fetch from `backend` token max multiplier using this endpoint  GET `/api/get-multipliers`
4. Depends on the value, limit max slider value 
Text me in telegram to get access to figma  `djeck_vorobey1`

**Comment by Josh-121** [comment]
Can I work on this? I like 🍒.

**Comment by mimisavage** [comment]
I would love to take this up. I like 🍒

**Comment by ikemHood** [comment]
Can I get this done,
I like 🍒

**Comment by Kaminar-i** [comment]
Would there be a chance for me to take on this issue?, I like 🍒

**Comment by SailorJhay** [comment]
Can I handle this task?
I like 🍒

**Comment by ooochoche** [comment]
@djeck1432 I would love to work on this

**Comment by omsant02** [comment]
i would like to take this issue. I like 🍒
i am planning to resolve this issue  by adding pre-built slider ui component from some component library such as Mui

**Comment by ikemHood** [comment]
💫
