### ISSUE TITLE
[Design] Create new page for documentation

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#192]
1. Create new page for documentation with next section:
- Overview
- Risks and conditions
- DeFI Spring Rewards

**Comment by Osatuyi** [comment]
can I be assigned this issue please.

**Comment by wheval** [comment]
Can i work on this?

**Comment by Iwueseiter** [comment]
Hi @djeck1432 can I work on the documentation when the UI had been implemented?
I’m a new contributor to this project and I’d love to work on this.

**Comment by 0xdevcollins** [comment]
Can I tackle this @djeck1432
