### ISSUE TITLE
[Backend] Create endpoint for subscription

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#194]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create new endpoint `subscribe_to_notification` in [user.py](https://github.com/djeck1432/spotnet/blob/main/web_app/api/user.py)
3. Parameters should be `telegram_id` and `wallet_id`
4. Add Serializer for input
5. Response could be `200`

**Comment by ShantelPeters** [comment]
Hi @djeck1432 can i please be assigned to this issue

**Comment by 0xdevcollins** [comment]
Hi @djeck1432 I can work on this

**Comment by blessingbytes** [comment]
pls can i work on this

**Comment by Benjtalkshow** [comment]
Hi @djeck1432  let me work on this.

**Comment by SudiptaPaul-31** [comment]
Can I get this issue assigned?

**Comment by Michaelkingsdev** [comment]
Can i work on this? I am a  contributor.  I like 🍎.

**Comment by Villarley** [comment]
Hey! I’m Santiago Villarreal, a developer from Costa Rica, a member of Dojo Coding, and a recent Buildathon winner with experience in creating APIs and managing data through serializers. I’m diving into Web3 and am excited about the chance to contribute.

For the subscribe_to_notification endpoint in user.py, here’s how I’d approach it:

Add the Endpoint: Define the subscribe_to_notification endpoint in user.py, setting it up to receive telegram_id and wallet_id as parameters.
Implement Serializer: Develop a serializer to validate and structure these inputs, ensuring data consistency.
Set Up Response: Configure the endpoint to return a 200 status code upon successful requests.
I’m excited to leverage my background and bring my skills to the team—feel free to reach out on my social media if you’d like to discuss further!

**Comment by mimisavage** [comment]
Can i work on this? I am a new contributor. I like 🍎.

**Comment by SudiptaPaul-31** [comment]
I like 🍎. Can I get this issue assigned?

**Comment by Michaelkingsdev** [comment]
Thanks. Will start working on it asap.

**Comment by djeck1432** [comment]
@Michaelkingsdev  You were assigned to this issue, you have 12 hours to create draft PR

**Comment by djeck1432** [comment]
@Michaelkingsdev https://t.me/+m0IGRiBvLtsyMzIy please, join to telegram group to keep in touch

**Comment by KevinMomanyi** [comment]
I like 🍎. 
Can I get this issue assigned?
