### ISSUE TITLE
[BACKEND] Create integration test for open position

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#196]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create new folder in root folder `integration_test` 
3. Create scenario to open position
4. To get real data, you should have:
- argent wallet
- some strk token (~1$) on your balance
- some eth token (~1$) on your balance
Feel free to reach me via telegram and I will send you to argent these amounts for testing
5. Run docker-compose to run frontend and backend
6. Open website and open position
7. Follow each step and look which endpoints are triggering to reproduce them in integration test
8. If there is missing some `console.log` of output of calling endpoint (add logs in FE code) to display it

Result:
1. Integration test should reproduce all steps with real/fake data to pass validation and call some out endpoints such as Ekubo to fetch `pool` data

**Comment by 0xdevcollins** [comment]
i can work on this. I like 🍎.

**Comment by Benjtalkshow** [comment]
let me take on this

**Comment by Josh-121** [comment]
Would perform necessary tasks.I like 🍎

**Comment by Benjtalkshow** [comment]
let me take on this

**Comment by mimisavage** [comment]
I like 🍎. Please let me work on this one @djeck1432

**Comment by ikemHood** [comment]
I would like work on this, I like 🍎,
I am an expericence software developer and a returning contributor
