### ISSUE TITLE
[BACKEND] Add sentry package to collect logs

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#203]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Install using poetry `sentry-sdk[fastapi]@latest`
3. Update `.env.example` with setnry_dsn` key
4. Add logic to run it only if it's `production` env not `dev` to avoid spamming 
 - Production env build with `docker-compose.yaml`
 How to do that:
 - add to `.env.dev` new variable, ENV_VERSION=DEV`
 - check it before init sentry_sdk, if `os.getenv("ENV_VERSION") == "DEV"` ignore it if other value, init sentry_sdk
 5. Use this code for init sentry in file [main.py](https://github.com/djeck1432/spotnet/blob/main/web_app/api/main.py):
 ```
 import sentry_sdk

sentry_sdk.init(
    dsn="https://None",
    traces_sample_rate=1.0,
    _experiments={
        "continuous_profiling_auto_start": True,
    },
)
```

**Comment by djeck1432** [comment]
@mexes20 you were assigned

**Comment by djeck1432** [comment]
@mexes20 Hi, any updates?

**Comment by djeck1432** [comment]
sorry, 12 hours are passed. @mexes20 you are unassigned

**Comment by 0xdevcollins** [comment]
Can I get this @djeck1432

**Comment by Benjtalkshow** [comment]
can i work on this

**Comment by Michaelkingsdev** [comment]
I would love to work on this please

**Comment by Villarley** [comment]
Hi @djeck1432 ,

I’m a Dojo Coding member and an active contributor to the OSS community. I’ve worked on several Web3 projects, including contributions to stellar projects, specifically building on StarkNet. I also have solid experience with React, and as a Web3 hackathon buildathon winner.

I would like to contribute to this python issue, because I want to start contributing to spotnet, and as I see is labeled for new contributors. I like 🍎🍎

**Comment by djeck1432** [comment]
@Criste-ai you were assigned and you have 12 hours to finish this task.

**Comment by djeck1432** [comment]
Hi @Criste-ai any updates?

**Comment by Criste-ai** [comment]
I need more time

**Comment by djeck1432** [comment]
@Criste-ai I will give you 2 more hours, task for 15 mins, just copy/paste and run one command and 10 mins for reading what is sentry and how it works.

**Comment by djeck1432** [comment]
@Criste-ai if you need any help just text me in DM in telegram `djeck_vorobey1`

**Comment by djeck1432** [comment]
@mexes20 sorry, it was unassigned you, so you will not have opportunity to contribute more for this issue.
If you have issue and you didn't notify me via telegram or here, how can I know about it? following the rule, you have 12 hours for doing this task. Your time has over

**Comment by djeck1432** [comment]
@mexes20 you don't have phone or access to telegram via it?

**Comment by bloomingpeach** [comment]
Can I work on this issue @djeck1432? I like 🍎.

**Comment by djeck1432** [comment]
@mexes20 last assigned contributor done it for 30 mins. as I mentioned above. easy task

**Comment by djeck1432** [comment]
@mexes20 I will give you one more try. but please, if you that something goes wrong, just drop a message in telegram.

**Comment by djeck1432** [comment]
@mexes20 texts me in telegram
djeck_vorobey1
