### ISSUE TITLE
[BACKEND] Add crud method and write test cases for endpoint

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#204]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add new crud method to [TelegramDBConnector](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L444) with name: `allow_notification` which will change field `is_allowed_notification` to `True` in `TelegramUser` model
3. Add this method to endpoint [here](https://github.com/djeck1432/spotnet/blob/main/web_app/api/user.py#L135)
4. Create test cases for [`subscribe_to_notification`](https://github.com/djeck1432/spotnet/blob/main/web_app/api/user.py#L117) negative and positive cases
5. Add test cases in this [file](https://github.com/djeck1432/spotnet/blob/main/web_app/tests/test_user.py)

**Comment by Benjtalkshow** [comment]
h

**Comment by djeck1432** [comment]
@Benjtalkshow You can't work on it, because it's for new comers, you have already done your task before. so please let new people on-board to the project too.

**Comment by bloomingpeach** [comment]
Hi, can I work on this issue @djeck1432

**Comment by djeck1432** [comment]
@bloomingpeach read guideline and reapply

**Comment by bloomingpeach** [comment]
May I work on the issue?
The issue involves adding new crud method to update the TelegramUser entity. After implementing the changes, I will have to write e2e test for the related controller/endpoint. 

Thanks for your consideration

**Comment by djeck1432** [comment]
@Benjtalkshow nope, sorry, if you can't read guideline properly, not sure that you can tackle this task
Read again GUIDELINE

**Comment by mimisavage** [comment]
I would like to work on this, I like 🍎.

**Comment by djeck1432** [comment]
@mimisavage you were assigned, please make sure that upcoming 12 hours draft PR will be ready, if you face any issue, text me in DM in telegram

**Comment by djeck1432** [comment]
> A new contributor, I like 🍎. Let me do this

new issue will be posted soon, follow us in telegram group to be up-to-dated https://t.me/+m0IGRiBvLtsyMzIy

**Comment by mimisavage** [comment]
> @mimisavage you were assigned, please make sure that upcoming 12 hours draft PR will be ready, if you face any issue, text me in DM in telegram

Okay sir

**Comment by djeck1432** [comment]
@mimisavage Hi, any updates, issue?

**Comment by djeck1432** [comment]
@mimisavage you will be unassign in an hour

**Comment by mimisavage** [comment]
Please, I'm making a PR now sir

**Comment by djeck1432** [comment]
@mimisavage you have 30 mins, after that you will be unassign

**Comment by djeck1432** [comment]
@mimisavage text me in telegram
