### ISSUE TITLE
[Backend] Create endpoint to check if user has already opened position

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#210]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add endpoint `has_user_opened_position` GET in this [file](https://github.com/djeck1432/spotnet/blob/main/web_app/api/user.py)
3. This method should have as input `wallet_id` and check in db if user has opened position or not.
4. Create crud method to get `boolean` value if user has opened position in [PositionDBConnector](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L209)
5. Return value `true` or `false` in response of endpoint.

**Comment by Benjtalkshow** [comment]
Anyone for old contributors?

**Comment by djeck1432** [comment]
Not at the moment, designing further features @Benjtalkshow

**Comment by Michaelkingsdev** [comment]
Please can i work on this sir. I  like 🍎🍎.

**Comment by caxtonacollins** [comment]
@djeck1432 i will love to be assigned this issue

**Comment by dev-chinx** [comment]
hey @djeck1432 can i hop on this

**Comment by petersdt** [comment]
Please can i work on this sir. I like 🍎🍎.

**Comment by dahtee** [comment]
can I work on this? I like 🍎.

**Comment by djeck1432** [comment]
@dev-chinx your account is just created. Not sure that you can't manage it

**Comment by djeck1432** [comment]
@dahtee I hope you read properly guideline, you have 12 hours to complete this task, based on this task we will have 2 others, so please, don't blocking us and do it quickly, any question pops up, just text me in telegram

**Comment by Ekene001** [comment]
I would like to work on this, I like 🍎.
