### ISSUE TITLE
[FRONTEND] Add pop-up window if position is already created

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#213]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create new pop-up window follow the figma (text me in telegram dm(djeck_vorobey1) your email, I will share it with you)
3. If user has already opened position, please, show user this pop-up
4. To get data if user has opened position, call `/api/has-user-opened-position` this endpoint which will return:
```
{"has_opened_position": True or False}
```
5. If user click on `Close active position` redirect to `Dashboard` page
6. Pop-up view
<img width="826" alt="Screenshot 2024-11-18 at 10 39 38" src="https://github.com/user-attachments/assets/66cd3468-5a58-4d7b-9156-2c23f27b2f56">

**Comment by 0xdevcollins** [comment]
Can I get this one @djeck1432

**Comment by PoulavBhowmick03** [comment]
I like 🍎
Would love to work on this!

**Comment by Jagadeeshftw** [comment]
I would like to work on this issue @djeck1432

**Comment by djeck1432** [comment]
@PoulavBhowmick03 you were assigned, please, text me to dm your email, to grant access to figma

**Comment by PoulavBhowmick03** [comment]
I like 🍎
Would love to work on this!

**Comment by PoulavBhowmick03** [comment]
> @PoulavBhowmick03 you were assigned, please, text me to dm your email, to grant access to figma

Sure ser

**Comment by Iwueseiter** [comment]
Hi @djeck1432 can I work on this? I like 🍎

**Comment by omsant02** [comment]
I would like to work on this issue @djeck1432,
I like 🍎

I would use the has_opened_position and data from the api to check and use logical conditions to conditionally render the output on the frontend

**Comment by ikemHood** [comment]
I can get this done in 12hrs, @djeck1432?
I like 🍎

**Comment by Kaminar-i** [comment]
hey @djeck1432 can i work on this issue
I like 🍎

**Comment by Akshola00** [comment]
Hi @djeck1432 , I would like to workk on this issue. I will create the pop-up window based on the Figma design. This window will show if the user has an active position by calling the /api/has-user-opened-position endpoint. If the user clicks "Close Active Position," they will be taken to the Dashboard page. I will implement this and efficiently for other devs to understand 
I like 🍎.

**Comment by wheval** [comment]
Hello @djeck1432, Can i fix this?
I like 🍎.
ETA is 1 day.

**Comment by Awointa** [comment]
available
