### ISSUE TITLE
[FRONTEND] Rework dashboard page 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#214]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Follow figma, rework dashboard page: 
3.  DO Not:
- change footer/header
- create mobile version
<img width="852" alt="Screenshot 2024-11-18 at 17 12 54" src="https://github.com/user-attachments/assets/2b392570-7993-4492-a1ac-1161630a9188">
4. Fetch data from `dashboard` endpoint as it was before ( pay attention to narrow, there are 2 options: green and red)
5. Text me in DM with your email to share with you access to figma

**Comment by raizo07** [comment]
Can I work on this?

**Comment by Benjtalkshow** [comment]
can i take this?

**Comment by 0xdevcollins** [comment]
I like 🍎 Can I take this

**Comment by KevinLatino** [comment]
My name is Kevin Latino, and I'm a frontend developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, and I recently won the LATAM Base Hackathon. I've also contributed to projects in ecosystems like Starknet and Stellar.

I like 🍒, and would love to help on this issue

**Comment by Jagadeeshftw** [comment]
Shall I work on this?

**Comment by caxtonacollins** [comment]
I like 🍒, please, i will love to work on this

**Comment by Jemiiah** [comment]
@djeck1432 i like 🍒 can I work on this issue

**Comment by Michaelkingsdev** [comment]
can i take this? I like 🍒

**Comment by Akshola00** [comment]
Hi @djeck1432 
I would like to work on this 
I love 🍅
