### ISSUE TITLE
Create Vault

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#221]
Your task is to create vault smart contract and implement basic logic, ownership system and upgradability.
Steps:
* Create the new vault.cairo file and define the new Vault contract there.
* Define storage with next fields: token: ContractAddress and amounts: Map<ContractAddress, TokenAmount>. token represents the token we going to store in the vault, and amounts will track how much each user stores now
* Add the constructor which will initialize owner and token address stored in this vault.
* Implement Upgradeable openzeppelin trait and assert operation is performed only by owner.
* Add the store_liquidity(amount: TokenAmount) method. It will transfer tokens from the caller to the vault, increase users amount in the corresponding storage variable and emit LiquidityAdded event with user and amount fields
* Add the withdraw_liquidity(amount: TokenAmount) method, which will do reverse operation and transfer amount back to the user
* Write tests for these two methods with positive and negative cases.
* Add docstrings and describe panics inside methods

**Comment by raizo07** [comment]
@djeck1432 can I work on this?

**Comment by bloomingpeach** [comment]
May I work on this issue @djeck1432?

My approach: I will do some revision on OZ Cairo contracts(ERC20, Upgradeable), and then I'll follow the issue instructions and implement basic Vault contract, also add extensive unit tests and proper documentation for the newly added methods.
