### ISSUE TITLE
[Frontend] logout window (desktop)

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#223]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add pop up window when user wants to log out
3. If user `click` on disconnet, disconnet its wallet
4. If user `click` on `cancel` close this pop-up window
5. Ask me in telegram(djeck_vorobey1) to get access to figma, send me your email in message

**Comment by Ayoazeez26** [comment]
Hi @djeck1432 I would like to work on this
I like orange
I would handle this by creating a modal when a user wants to logout to match the figma design accurately
I would make sure all functionalities work as intended before making a PR
ETA - 1 day
