### ISSUE TITLE
[Frontend] Notification window (desktop/mobile)

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#224]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Ask me in telegram(djeck_vorobey1) to get access to figma, send me your email in message
3. Add pop-up window to enable notification in telegram (mobile/desktop) versions
4. If user click on `YES, SURE` send request to next endpoint on backend `/api/subscribe-to-notification` with next params:
`telegram_id` and `wallet_id`

**Comment by Ibinola** [comment]
Hi @djeck1432 I would like to work on this
I like orange
I would inspect the figma to know where to add the pop-up window
I would make sure the implemented function, sends a request to the endpoint with the necessary params

**Comment by Tzienom** [comment]
Hi, I'm Gabriel and I would like to work on issue #224.

This task can be accomplished in 48 hours.

I would create a component that pops the notification window and redirects them appropriately based on their click. This will be my first time contributing to a project.

**Comment by Ibinola** [comment]
Hi @djeck1432 , I have access to the `wallet_id`  from the `useEffect `on the dashboard, but not the `telegram_id`
