### ISSUE TITLE
[Frontend] Dashboard mini-app

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#225]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Ask me in telegram(djeck_vorobey1) to get access to figma, send me your email in message
3. Add design for dashboard for mobile versions
4. Make sure all endpoints work as before

**Comment by System625** [comment]
Hey I would like on this issue as a new contributor
I will add the design for the mobile screens and I will get a draft PR ready in 12 hours and I like orange
