### ISSUE TITLE
[Frontend] Create position mini-app

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#226]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Ask me in telegram(djeck_vorobey1) to get access to figma, send me your email in message
3. Add create position(form) for mobile version 
4. Make sure all endpoints work as before

**Comment by wheval** [comment]
Hello @djeck1432, I'm Wheval a frontend developer. I want to work on this. 
I like orange. I would make sure all the endpoints work. Please assign.

**Comment by wheval** [comment]
Thanks!.

**Comment by djeck1432** [comment]
@wheval you will be unassign in a hour, prepare your draft PR as soons as possible

**Comment by wheval** [comment]
okay, i'm on it.
