### ISSUE TITLE
[Devops] Setup CD pipeline

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#238]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create CD pipeline to deploy project to the server
3. Build docker-compose  only for `main` branch
4. Connect to the server
5. Run up container

**Comment by joanne-cmd** [comment]
hello, i am  joanne, have a background devops and i would love to work on this issue
