### ISSUE TITLE
[FRONTEND] New position window mini-app

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#242]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add new window for pop-up for `mobile device` if user click on `submit form` and user has already opened position
3. Redirect user to dashboard to close position
4. Ask me in telegram(djeck_vorobey1) to get access to figma, send me your email in message

**Comment by DanielEmmanuel1** [comment]
Can I jump on this task?

Hello I'm a new contributor and would like the opportunity to work on this
I am a frontend developer with experience in creating neat UI designs.

**Comment by Supa-mega** [comment]
Can I work on this, please?

**Comment by ekumamatthew** [comment]
Is it okay if I tackle this? I like oranges

**Comment by OWK50GA** [comment]
Can I attempt this issue?
I like orange
Can I attempt this issue?
I will go to the submit handler of the form, and add the condition that if a position has already been opened, the user should see a popup instead that redirect shows the option for the user to go to dashboard and close position, depending on how the Figma shows it

**Comment by NueloSE** [comment]
I like orange 

kindly assign me this task

**Comment by mayasimi** [comment]
I'd like to handle this task.

I like orange 

let me work on this task

**Comment by petersdt** [comment]
I like orange .

kindly assign me this task am a frontend developer with experience using js and typescript

**Comment by deeseeker** [comment]
This is an issue I can handle but I will be needing more descriptions and I will like to see the mockup design. I have 2 years of experience in JS,TS, next js and React and I have very good eyes for converting interactive and responsive design.

Let me take this issue
