### ISSUE TITLE
[Tester] Create scenario for manual testing

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#244]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Install `Argent X` and `Bravos` extension in your browser
3. Create file in root folder ` manual_test_scenarios.md`
4. You should describe next flows:
- Connect to different wallets (Argent, Bravos)
- Open Position with different wallets (so you need to have a little STRK tokens and ETH)
- Close Position with different wallets
- Open position with different tokens
- Try to open position if you have already done it before 
5. Your scenarios should guide us one by one step to reproduce this flow in the future for better manual testing before release.
6. If you find any bug, report it in file also
7. If you see any further scenario which makes sense, add it also there 
8. Please, set up project locally using dev container as it's described in README.md

**Comment by mayasimi** [comment]
"I like orange Can I start working on this testing i have experience in web application testing from test.io?

**Comment by Kaminar-i** [comment]
Could I take on this issue?
i like orange 
kindly assign

**Comment by Tzienom** [comment]
@djeck1432 I like orange. I would like to work on this issue.

**Comment by petersdt** [comment]
i like orange, kindly assign me to join on this manual testing 

i have read through your guideline and have bravoos and arget wallet kindly assign

**Comment by djeck1432** [comment]
@Kaminar-i You were unassigned, I can't see draft PR

**Comment by NueloSE** [comment]
Am avaliable 4 this

**Comment by Tzienom** [comment]
@djeck1432 I like orange. I would like to work on this issue.

**Comment by petersdt** [comment]
@djeck1432 am still avaliable to take this issue because i like grapes

**Comment by Judah04** [comment]
@djeck1432 I like grapes. Can I would work on this issue?

**Comment by Judah04** [comment]
> @djeck1432 I like grapes. Can I work on this issue?

**Comment by Tzienom** [comment]
@djeck1432 I like grapes. I would like to work on this issue.

**Comment by Birdmannn** [comment]
Hey @djeck1432 , I like cherry, Please can I work on this issue? I would make a draft PR within 10 hours of assignment, and please if I have further questions on this assignment, I will always be in touch with you. But following the steps, it should be a "good to go" situation. Thank you very much.

**Comment by caxtonacollins** [comment]
am applying through the onlydust platform
Can I take this issue?

**Comment by caxtonacollins** [comment]
@djeck1432 I like cherry, i will love to take this issue. Please assign me

**Comment by djeck1432** [comment]
@pheobeayo you were unassigned, you didn't create draft PR within 12 hours

**Comment by Judah04** [comment]
@djeck1432 I would like to work on this, I like cherry.

**Comment by Xaxxoo** [comment]
I'd love to give this a go.

**Comment by olisaagbafor** [comment]
Is this issue still available?
I like cherry.
https://t.me/olisaagbafor

**Comment by deeseeker** [comment]
I like orange.

Can I work on this task? I will test all scenarios carefully.

**Comment by Supa-mega** [comment]
May I take this issue on?

**Comment by petersdt** [comment]
@djeck1432 let me help you with the manual test, because i like cherry kindly assign me ETA <= 10hrs

**Comment by chigozzdevv** [comment]
Mind if I take this issue? I LIKE CHERRY. I'm a new contributor.
Telegram handle: chigozzdevv

**Comment by Shalomnze** [comment]
I'd love to give this a go  as my first project. 
i currently have Argent and bravos wallets extension installed in my laptop. 
i have some strk tokens available which i woiuld use for this test. Thank you
