### ISSUE TITLE
[BACKEND] Create test cases for DepositDBConnector

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#245]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create test cases for DepositConnector positive and negative scenarios
3. Create new file deposit_db_tests.py in this [folder](https://github.com/djeck1432/spotnet/tree/main/web_app/tests/db)
4. Feel free to use mock from [`confest.py`](https://github.com/djeck1432/spotnet/blob/main/web_app/tests/conftest.py)

**Comment by ikemHood** [comment]
Can I take this,
I like orange

**Comment by Jagadeeshftw** [comment]
I’d like to help with this. I like orange

**Comment by olisaagbafor** [comment]
I'd like to handle this task. 
I like grapes.
