### ISSUE TITLE
[Backend] Add new vault endpoints

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#246]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add new endpoint `get_user_vault_balance` in [vault.py](https://github.com/djeck1432/spotnet/blob/main/web_app/api/vault.py) which will have `wallet_id` parameter and will return amount of tokens in response
3.Add new endpoint `add_vault_balance` which will have as parameters `wallet_id` and `amount`   and will update `user vault balance`
4. All needed method to database you can find in this [`DepositDBConnector`](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L647)
5. Please, don't forget to create Request and Response pydantic models for each endpoint

**Comment by olisaagbafor** [comment]
I’d love to work on this task. I like grapes

**Comment by Jagadeeshftw** [comment]
Let me handle this issue! I like grapes

**Comment by petersdt** [comment]
Can I take this issue?

**Comment by Tzienom** [comment]
@djeck1432 I like grapes. I am a first time contributor and would like to work on this issue.

**Comment by NueloSE** [comment]
@djeck1432 can i handle this issue I like grapes
