### ISSUE TITLE
[Backend] Create integration test for Close position

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#251]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. In this [folder](https://github.com/djeck1432/spotnet/tree/main/web_app/tests/integration_tests) create new file `test_close_position.py`
3. Make sure to test on real data, like create fake instance and save result to db
4. Remove all test instances after running tests

**Comment by binayak9932** [comment]
I think i can work on this btw I like cherry.
