### ISSUE TITLE
[DEVOPS] Create github pipeline for running integration test

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#252]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create new github workflow for running integration test
3. Make sure that you set up connection to db
4.  Integration test [folder](https://github.com/djeck1432/spotnet/tree/main/web_app/tests/integration_tests)

**Comment by raizo07** [comment]
Kindly assign me, I like cherry

ETA: 10 hours
