### ISSUE TITLE
[Backend] Create test cases for vault endpoints

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#254]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create test cases: positive and negative scenarios for vaults endpoints which you can find [here](https://github.com/djeck1432/spotnet/blob/main/web_app/api/vault.py)
3. Create new file `test_vaults.py` in this [folder](https://github.com/djeck1432/spotnet/tree/main/web_app/tests)
4. For mocking DB connection, feel free to reuse from [confest.py](https://github.com/djeck1432/spotnet/blob/main/web_app/tests/conftest.py)

**Comment by Jagadeeshftw** [comment]
I would like to work on this issue, I like cherry

**Comment by Judah04** [comment]
@djeck1432 I like cherry. I would love to work on this task.

**Comment by petersdt** [comment]
@djeck1432 kindly assign me because i like cherry
