### ISSUE TITLE
[Research] discover how we can start using Flash Loan on Ekubo 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#257]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create new `file` ekubo_research.py in this [folder](https://github.com/djeck1432/spotnet/tree/main/web_app/contract_tools)
3. Read documentation Ekubo about [Flash loan](https://docs.ekubo.org/about-ekubo/key-concepts#free-flash-loans)
4. Suggest how we can rework [`get_transaction_data`](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/mixins/deposit.py#L21) to use Flash Loan instead
5. In your file `ekubo_research.py ` should be described some flow from documentation in code, so later on we can write code based on your examples( triggering specific endpoints, response data of them)

**Comment by petersdt** [comment]
can i work on this I like cherry

**Comment by Judah04** [comment]
@djeck1432 I like cherry, can I please be assigned to this issue?

**Comment by BrunoAmbricca** [comment]
I’d like to work on this. I like cherry

**Comment by djeck1432** [comment]
@Judah04 any updates? I can't see your draft PR
