### ISSUE TITLE
[Backend] Add new fields and crud methods for Position/PositionDBConnector

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#258]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. In [Position](https://github.com/djeck1432/spotnet/blob/main/web_app/db/models.py#L57) add new fields:
- is_protection_on, type boolean, default value is False
- liquidation_bonus, type float, default value is 0.0
- is_liquidated, type boolean, default value is False
- datetime_liquidation, type datetime, nullable=True
3. Add migrations file, how to do that, you can find [here](https://github.com/djeck1432/spotnet/blob/main/README.md#how-to-create-migration-file)
4. Add new crud method in [PositionDBConnector](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L233)
- `liduate_position` with parameters (position_id) will change value of `is_liquidated to True and will set current time datetime_liquidation
- `get_all_liqauted_position` -> will returl all position where `is_liquidated` is True

**Comment by Judah04** [comment]
@djeck1432 I like cherry, can you assign this to me?

**Comment by Kaminar-i** [comment]
hey @djeck1432 i like cherry 
assign me
