### ISSUE TITLE
[Backend] Create endpoint get user history

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#259]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create endpoint [`users.py`](https://github.com/djeck1432/spotnet/blob/main/web_app/api/user.py) `get_user_history` get endpoint.
3. This endpoint will return all positions with next fields:
- `status`
- `created_at`
- `start_price`
- `amount` 
- `multiplier`
4. In [`UserDBConnector`](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L128C7-L128C22) add new crud method to fetch all those data

**Comment by vestor-dev** [comment]
holla @djeck1432 i like cherry
kindly assign 
TG https://t.me/chidex2111

**Comment by Kaminar-i** [comment]
hey @djeck1432 would love to work on this issue 

i like cherry 
ETA: <= 10hrs

**Comment by amJoe-dev** [comment]
I love to work on this issue and ensure it delivered with 12 hours "I like cherry."

**Comment by No-bodyq** [comment]
May I take this issue on? I like cherry t.me/No_body_q
