### ISSUE TITLE
[Frontend] Add withdraw staking page (desktop)

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#266]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Following figma, add withdraw page 
<img width="671" alt="Screenshot 2024-11-25 at 18 30 21" src="https://github.com/user-attachments/assets/64dfaa5f-9ba3-4f2b-8d3d-e71130a51643">

3. Please, do not add left side bar, it will be done by another contributor
4. Make sure, that your form is responsive till mobile sizes
5. Text me in DM in telegram(djeck_vorobey1) to get access to figma, in your message write your email please

**Comment by Jagadeeshftw** [comment]
Shall i take this issue, I like cherry.

**Comment by bebofit** [comment]
I would like to work on this, I like cherry

**Comment by djeck1432** [comment]
@bebofit please, send me your email to get access to figma you have limited time to create PR

**Comment by AdejareSamad** [comment]
I like cherry, I would like to work on this. I am a new contributor.
