### ISSUE TITLE
[Design] Create design for Vault 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#267]
1. Create design for vault
2. Add new page `vault` to header
3. Add form for staking 
4. Add form for withdrawing

**Comment by 0xdevcollins** [comment]
Can I work on this. I like cherry

**Comment by Jagadeeshftw** [comment]
Could I grab this task?, I like cherry

**Comment by Osatuyi** [comment]
Can I be assigned this issue, please?
I'm a web3 product designer and I can deliver a good job in time.

**Comment by Luluameh** [comment]
Hello @djeck1432  I  will love to work on this, kindle assign me this issue

**Comment by SudiptaPaul-31** [comment]
@djeck1432 Can I get this issue?
