### ISSUE TITLE
[Backend] Create test cases for new  crud methods

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#268]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create test cases for these methods in appropriate files in  [`tests`](https://github.com/djeck1432/spotnet/tree/main/web_app/tests/db) folder:
- [`delete_all_users_airdrop`] - https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L686
- [`delete_all_user_positions `] - https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L634
- [`delete_object`] -  https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L117

**Comment by nora360** [comment]
I'd love to give this a go.
I like cherry.
@olisanora

**Comment by petersdt** [comment]
@djeck1432 can i work on this I like cherry

**Comment by obacollins-lab** [comment]
Can I jump on this task? I like cherry.
Telegram handle: @Djjaiye

**Comment by petersdt** [comment]
@djeck1432 can i be assigned this i like cherry TG: @joe_yanum

**Comment by Kingsuite** [comment]
@djeck1432 i can handle this task I like cherry

**Comment by Elsie-ND** [comment]
@djeck1432 Kindly reassign me  I have a PR but I mistakenly unassigned.

**Comment by djeck1432** [comment]
@Elsie-ND Where is your PR?

**Comment by djeck1432** [comment]
more 2 hours and you will be unassign @Elsie-ND

**Comment by djeck1432** [comment]
@Elsie-ND Don't get your question text me in Telegram
okay, 6hr
