### ISSUE TITLE
[Backend] add claim airdrop to celery 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#272]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
3. Add to background  task for claiming airdop code is [here](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/airdrop.py#L65)
4. Use this [code](https://github.com/djeck1432/spotnet/blob/main/web_app/tasks/claim_airdrops.py#L19) to fetch and update airdrop instance 
5. Create test cases for this class, positive and negative scenarios 
6. Use this [file](https://github.com/djeck1432/spotnet/blob/main/web_app/tests/conftest.py) for mocking db connection

**Comment by Abeeujah** [comment]
Is this issue still available?, I'd love to work on it, I like cherry
