### ISSUE TITLE
[Backend] Refactoring crud methods

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#273]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create [here](https://github.com/djeck1432/spotnet/tree/main/web_app/db) new folder `crud` 
3. Add `__init__.py` file
4. Add `position.py`
5. Add `user.py`
6. Add `airdrop.py`
7. Add `telegram.py` 
8. Add `deposit.py`
9. Add `base.py` for `DBConnector` class
10. Move to appropriate folder each class from [`crud.py`](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py) for example `position.py` -> `PositionDBConnector`
11. In `__init__.py` add all imports from each new files.

**Comment by obacollins-lab** [comment]
Can I take care of this issue? I'm proficient in python and  a new contributor to this project.
I like cherry
