### ISSUE TITLE
[Backend] Update populate with seed_data for new models

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#274]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Revise [`seed_data.py`](https://github.com/djeck1432/spotnet/blob/main/web_app/db/seed_data.py) and add missing new models(fields) from this [file](https://github.com/djeck1432/spotnet/blob/main/web_app/db/models.py) 
3. Make sure that you create fake data which makes sense, for example, for wallet_id instead of hex insert some `example` string, so data should be consistently and help contributors to on-board easier 
4. Create 10 per new models, pay attention, that some fields are related to another objects.

**Comment by emarc99** [comment]
I like cherry, and your telegram handle is emarc99.
I will first study code well, proceed after comprehension.
I will add missing models to seed_data, then use fake data to help contributors to on-board easily. Test code is working correctly.

**Comment by Tzienom** [comment]
@djeck1432 kindly assign I like cherry. TG: mohammed nasiru

**Comment by amJoe-dev** [comment]
Can I be assigned to this?

**Comment by Kingsuite** [comment]
@djeck1432 I can handle this I like cherry

**Comment by djeck1432** [comment]
@Kingsuite ping ping, share with me your telegram handler

**Comment by Kingsuite** [comment]
t.me/thedavidajayi
