### ISSUE TITLE
[Backend] Add background task for send notification if health_ratio_level is too low

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#275]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add background task [here](https://github.com/djeck1432/spotnet/blob/main/spotnet_tracker/tasks.py)
3. This task should check if health_ratio level is below normal using this [code](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/mixins/alert.py)
4. Add new crud method to [TelegramUser](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L701) is_allowed_notification where parameter will be `wallet_id` and will return true or false
5. add new method to mixin `send_notification` where you will be check if telegram_user.is_allowed_notification 
6. Add TODO add sending telegram message if user allowed to send notification inside `send_notification` method

**Comment by MooreTheAnalyst** [comment]
Hello, can i be assigned this issue?
