### ISSUE TITLE
[Frontend] Create global store for walledId

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#278]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Please extract walletId from [here](https://github.com/djeck1432/spotnet/blob/main/frontend/src/App.jsx) to a separate store, using [Zustand](https://github.com/pmndrs/zustand)
3. Create a new folder in src called stores and call the file useWalletStore.js, useWalletStore should consist of walletId and setWalledId.
4. Default value of walletId should be taken from localStorage (just like now). And on setWalletId action - it should set walletId to both zustand store and localStorage.
5. Go through all the files, starting from the [root](https://github.com/djeck1432/spotnet/blob/main/frontend/src/App.jsx) and make sure that wallet is no longer passed as a prop to child components/routes and everything is used from a store-hook. Instead, use useWallet store directly in files, where it is needed and avoid prop drilling.
6. Make sure everything works just like before and functioning well.

**Comment by Michaelkingsdev** [comment]
I’m interested in this one. I like cherry.

**Comment by Xaxxoo** [comment]
I'm interested in this one. Can I take it up? I like cherry.

**Comment by Kingsuite** [comment]
Can I attempt this issue?

**Comment by petersdt** [comment]
@djeck1432 can i take this like cherry

**Comment by Tzienom** [comment]
@djeck1432 i like cherry can i work on this

**Comment by djeck1432** [comment]
@Xaxxoo Sorry, you were unassigned

**Comment by 0xdevcollins** [comment]
Can I work on this? I like cherry

**Comment by Michaelkingsdev** [comment]
Can i work on this? I like cherry

**Comment by josephchimebuka** [comment]
Can I take this one ser I like 🍒

**Comment by Benjtalkshow** [comment]
@djeck1432 Let me work on this please. I like cherry

**Comment by Jemiiah** [comment]
@djeck1432 i love 🍒 can i work on this issue 
ETA: 24 hrs

**Comment by Tzienom** [comment]
@djeck1432 am still avaliable for this issue i like cherry

**Comment by amJoe-dev** [comment]
@djeck1432 I like cherry, ill really love to work on this

**Comment by Ayoaris** [comment]
@djeck1432 

I like cherry, I would like to pick up this task.

Ayosoft

**Comment by Luluameh** [comment]
@djeck1432 can i take this like cherry
