### ISSUE TITLE
[Frontend] Improve Connect Wallet Action usage

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#279]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Move handleConnectWallet actions from [App.jsx](https://github.com/djeck1432/spotnet/blob/main/frontend/src/App.jsx) and [Form.jsx](https://github.com/djeck1432/spotnet/blob/main/frontend/src/pages/forms/Form.jsx) to a custom hook using [useMutation](https://tanstack.com/query/v4/docs/framework/react/reference/useMutation), name it useConnectWallet and put it into hooks folder.
3. This hook should contain both connectWallet and checkForCRMToken actions, onSuccess it should put set walletId via a setWalledId function that will be passed to useConnectWallet.
4. On success or on error you should notify user using notification functions from [here](https://github.com/djeck1432/spotnet/blob/main/frontend/src/utils/notification.js). Success message - Wallet successfully connected | Error message - Failed to connect wallet. Please try again.
5. You should put [Notifier](https://github.dev/djeck1432/spotnet/blob/main/frontend/src/utils/notification.js) component to [App.jsx](https://github.com/djeck1432/spotnet/blob/main/frontend/src/App.jsx), so it is global and all notifications are displayed correctly.
6. Use this hook correspondingly in both App and Form components
7. Make sure everything works just like before and functioning well.

**Comment by Michaelkingsdev** [comment]
Can I handle this task?

**Comment by Pvsaint** [comment]
May I be assigned to this?
I'm a first time contributor

**Comment by Michaelkingsdev** [comment]
I’m interested in this one. I like cherry

**Comment by NowGoody** [comment]
@djeck1432 can i take this  like cherry

**Comment by Kingsuite** [comment]
Let me try this one!

**Comment by petersdt** [comment]
@djeck1432 can i take this like cherry

**Comment by helios492** [comment]
Hello! @djeck1432 
I have great expertise in integrating wallet connect functionality using wagmi, raibowkit and ether.js.
With my previous work experience, I am confident that I can handle this issue asap.
Plz assign me this issue

**Comment by Ibinola** [comment]
I would like to work on this
I like cherry
I will the move the necessary handleConnectWallet `actions` to a custom hook and `useMutation`, name it `useConnectWallet` and place it in the hooks folder.
I will add the appropriate notifiers(on success and on error) of the actions 
I will place the Notifier in my App component so it is global and all notifications are displayed correctly.

@ibinolamichael
