### ISSUE TITLE
[Frontend] Create generic Button component

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#280]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1.Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Currently accross the app we have the same buttons on ([Dashboard](https://github.com/djeck1432/spotnet/blob/main/frontend/src/pages/spotnet/dashboard/Dashboard.jsx) and [Form](https://github.com/djeck1432/spotnet/blob/main/frontend/src/pages/forms/Form.jsx) pages, please replace every occurence on that pages (please also check all child components) with a generic Button component according to Figma design.
3. It should consume variant prop, as you can clearly see there are two types of button, one is with gradient (call it primary) and another one is outlined/transparent (call it secondary).
4. It should also have size prop which, by Figma you can also clearly see, that there are couple of different sizes, so it'll be lg | md | sm and based on that prop, you should set corresponding size in css (642 | 342/309 (depending if mobile or desktop) | 167)
5. It should also accept spreaded props [e.g. { variant, size, ...props }] which will be passed to a button, so basic html button attributes are inherited
6. Button's content should be passed as React's children, [e.g. <Button ...(props)>Button Name</Button>] and consumed correctly inside the component.
7. Make sure everything is done according to Figma in terms of sizes and colors and also functioning well, just like before.
8. Text me in DM in telegram(djeck_vorobey1) to get access to figma, in your message write your email please

**Comment by Ibinola** [comment]
I would like to work on this
I like cherry
I will first create the reusable button component in the components folder, it will the necessary props passed to it
I will then replace the regular buttons across my app with the reusable button component created

**Comment by NowGoody** [comment]
@djeck1432 can i work on this

**Comment by Xaxxoo** [comment]
I would like to work on this
I like cherry
I will first create the reusable button component in the components folder, it will the necessary props passed to it
I will then replace the regular buttons across my app with the reusable button component created

**Comment by petersdt** [comment]
@djeck1432 can i take this like cherry

**Comment by BoltUltra** [comment]
I will create a reusable Button component with variant and size props based on Figma designs, replace all occurrences on Dashboard and Form pages (including child components), ensure full functionality and styling match the design, and submit progress within the required timeframe.
I like cherry

Telegram handle: @Dami101a

**Comment by Luluameh** [comment]
@djeck1432 can I be assigned this issue?

**Comment by Tzienom** [comment]
@djeck1432 i like cherry can i work on this

**Comment by helios492** [comment]
Hello! @djeck1432 
I have great expertise in frontend development for blockchain project and also web 3 part.
I am eager to work for this issue and I am sure I can satisfy you with my this first issue.
I will complete this task asap.

**Comment by Ayoaris** [comment]
@djeck1432 

I would like to work on this project. I like cherry.

First, I will create a reusable button component in the components folder, making sure it accepts the necessary props. Then, I will replace the regular buttons across the app with the newly created reusable button component.

telegram: @AyoSoft
