### ISSUE TITLE
[Frontend] Fix dashboard mobile layout

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#290]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Fix broken mobile layout on [Dashboard page](https://github.com/djeck1432/spotnet/blob/main/frontend/src/pages/spotnet/dashboard/Dashboard.jsx).
<img width="553" alt="Screenshot 2024-11-27 at 21 48 50" src="https://github.com/user-attachments/assets/32763f8b-8c2e-4b33-b37f-255653b70e37">

3. Make sure everything is done according to figma. (paddings, sizes, card shapes)
4. Please rename `main-container` and `main-card` classes to something more **dashboard**-related so styles from other components (as for now withdraw.css or logoutModal.css) do not override dashboard's styles.
5. Text me in DM in telegram(djeck_vorobey1) to get access to figma, in your message write your email please

**Comment by OWK50GA** [comment]
Hi, I'll like to work on this.
I like cherry

**Comment by Ayoaris** [comment]
I would like to take on this task

I like cherry

Ayosoft

**Comment by aurlic** [comment]
Hey, I would love to get to work on this issue.
I'm a beginner on OnlyDust and would be really grateful to be able to tackle this issue down. I am a student at school 42 and am also currently learning Cairo and Rust. I have had the occasion to work on some FrontEnd before during some school projects and would be happy to test my skills and learn more during the resolving of this issue.
If I get assigned I will first test to identify the issue and then I will work towards fixing it and making everything as requested.
My telegram handle is @Arluc and one think you should know about me is that I like cherry.
