### ISSUE TITLE
[Frontend] Fix test cases on FE and adjust open position css styles in mobile design

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#291]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Fix test cases on Frontend
2. Make design the same way as it in figma

**Comment by whateverfw** [comment]
I'd love to work on this! I like cherry.

**Comment by Thibrac** [comment]
Can I contribute to this one?
