### ISSUE TITLE
[Frontend] Fix mobile header popups

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#294]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Fix broken mobile header popups. They should not overlap a content of a page, examples how it is currently broken:
<img width="536" alt="Screenshot 2024-11-28 at 8 49 19" src="https://github.com/user-attachments/assets/aa14c545-547f-471a-8d00-fc226f365bde">
<img width="530" alt="Screenshot 2024-11-28 at 8 49 35" src="https://github.com/user-attachments/assets/c092f462-38c3-4662-af50-3d83bfe63bb9">
3. Also please fix dropdown menu dropdown according to figma, there should not be any background on the back.
4. Verify that this works correctly on every page (main, dashsboard, form), 
5. Text me in DM in telegram(djeck_vorobey1) to get access to figma, in your message write your email please

**Comment by nora360** [comment]
May I pick this up?
I like cherry.

**Comment by amJoe-dev** [comment]
I'd like to take this issue.

**Comment by KVMillz** [comment]
@djeck1432 I like cherry, I would like to work on this. I am a first time contributor. TG: @KVMillz

**Comment by Tzienom** [comment]
@djeck1432 can i handle this

**Comment by djeck1432** [comment]
@Tzienom just friendly reminder, that in 3 hours you will be unassigned if you don't create draft PR

**Comment by Agbeleshe** [comment]
@djeck1432 can I take this like cherry?
This would be nice to have as my first contribution to the spotnet draft in less than 8 hours.
base on the code react js was used and also boostrap I am exprience in that and  also  responsiveness.  Can  i handle this?
@Bioba_dan telegram handle

**Comment by Oshioke-Salaki** [comment]
I can do it

**Comment by whateverfw** [comment]
I like cherry, I'd like to fix this

**Comment by OWK50GA** [comment]
I like cherry. Let me fix this
