### ISSUE TITLE
[Frontend] Vault withdraw page [mobile]

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#295]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Please make our current **Vault withdraw page** responsive for mobile/tablet devices.
<img width="344" alt="Screenshot 2024-11-28 at 8 51 27" src="https://github.com/user-attachments/assets/100454f1-b83b-41f5-bb3c-4818a0b0fb29">

3. Make sure your changes don't break anything in already created desktop version.
4. Verify mobile styles correspond to figma and look exactly the same.
5. Don't implement bottom navigation bar, just a page main content, nothing else.
6. Text me in DM in telegram(djeck_vorobey1) to get access to figma, in your message write your email please

**Comment by KVMillz** [comment]
@djeck1432 I like cherry, I would like to work on this. I am a first time contributor. TG: @KVMillz

**Comment by Ibinola** [comment]
Can I work on this ? @djeck1432

**Comment by josephchimebuka** [comment]
Can I work on this @djeck1432

**Comment by Benjtalkshow** [comment]
@djeck1432 Let me take this. I like cherry
