### ISSUE TITLE
[Frontend] Create Overview page [Desktop]

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#296]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create **desktop only** version for overview pages according to figma.
3. We have very similar Documentation page, you should take `TableOfContent` and `Section` components from [here](https://github.com/djeck1432/spotnet/tree/main/frontend/src/pages/spotnet/documentation) and move them to `components` folder, making them generic.
4. 5. You should create new `Sections` component which will consume array of sections as props and render each in an individual (already existing) `Section` component.
5. They should consume different content as props and be used correctly on both Documentation and Section pages (as well as `ScrollButton` component).
6. Make all your changes work correctly on both pages and everything is done according to Figma.
7. Text me in DM in telegram(djeck_vorobey1) to get access to figma, in your message write your email please

**Comment by nora360** [comment]
May I pick this up?
I like cherry.

**Comment by amJoe-dev** [comment]
Can I work on this, please?

**Comment by petersdt** [comment]
@djeck1432 let me handle this I like cherry.

**Comment by jahrulezfrancis** [comment]
@djeck1432 I would love to work on this.
tg: @jahrulez
