### ISSUE TITLE
[Frontend] Rework slider on a Form page

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#297]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Rework [MultiplierSelector component](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/MultiplierSelector.jsx) according to figma.
3. It should be fixed/reworked for both desktop and mobile devices. Slider max value should be based on the selected token, make sure that selected value can't be above max token's multiplier.
4. Slider step should be changed to 0.1 and small tooltip should be shown above a point.
5. Slider colors should be done according to figma.
6. Make sure you don't break anything else on this page and request to a backend still submits with correct values (especially correctly selected multiplier from a slider)
7. Text me in DM in telegram(djeck_vorobey1) to get access to figma, in your message write your email please

**Comment by nora360** [comment]
Could I grab this task?
I like cherry.

**Comment by Tzienom** [comment]
@djeck1432 let me do thisI like cherry.

**Comment by Thibrac** [comment]
Can I take care of this issue?

**Comment by djeck1432** [comment]
@Tzienom Please, read guideline

**Comment by Luluameh** [comment]
@djeck1432  can I work on this like Cherry?

**Comment by Jemiiah** [comment]
@djeck1432 pls can I work on this issue I’m an old contributor to this repo

**Comment by petersdt** [comment]
@djeck1432 let me handle this I like cherry.

**Comment by Thibrac** [comment]
Hey I would be happy to give this issue a go, I'm currently learning Cairo through Node Guardians and Im a student at 42.
If i was given this issue I would fix it using the reference on figma.
I would love to perfect skill in front end development and this would be a great way to do it.
I love cherry and my telegram is @Thibrac

**Comment by Agbeleshe** [comment]
@Thibrac Hello, i would love to work on this issue and make this my first contribution. Thank you

**Comment by djeck1432** [comment]
@Agbeleshe please, read guideline before applying

**Comment by KVMillz** [comment]
@djeck1432 I like cherry, I would like to work on this. I am a first time contributor. TG: @KVMillz

**Comment by djeck1432** [comment]
@Thibrac  just friendly reminder, that in 3 hours you will be unassigned if you don't create draft PR
