### ISSUE TITLE
[Frontend] Create Generic ActionModal

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#298]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create Generic/Reusable `ActionModal` component and put it inside a `components/ui` folder, please make sure to have both `ActionModal.jsx` and `index.js` components (please take a look how button is re-exported, do it the same way). 
This component should replace our current [Logout](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/Logout/LogoutModal.jsx), [Close Position](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/ClosePositionModal/CloseMositionModal.jsx) and [TelegramNotificationModal](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/TelegramNotificationModal/TelegramNotificationModal.jsx) (all which should be removed)
3. Instead of them use newly created modal component, that should consume following props: `title` (string), `subTitle`(string), `content` (array of strings that will be rendered as paragraphs), `cancelLabel`, `cancelAction`, `submitLabel`, `submitAction`, `isLoading` (optional). Pass corresponding props in the previous places of usage.
4. Make sure styles are working well both on desktop and mobile devices, according to figma (if not - please fix them).
5. Clicking outside the modal should also close it.
6. Make sure everything functioning well and all actions are correctly executed, just like with old modals.
7. Text me in DM in telegram(djeck_vorobey1) to get access to figma, in your message write your email please

**Comment by Oshioke-Salaki** [comment]
Pl

**Comment by David-Anaja** [comment]
Please can i do this. I am new to the OD platform

**Comment by jahrulezfrancis** [comment]
@djeck1432 I would love to work on this. I have worked with modals a lot, and I am sure this won't be much different.

**Comment by djeck1432** [comment]
@Oshioke-Salaki just friendly reminder, that in 3 hours you will be unassigned if you don't create draft PR
