### ISSUE TITLE
[FRontend] Vault Stake page [mobile]

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#304]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Please create mobile/tablet version for [Vault Stake page](https://github.com/djeck1432/spotnet/blob/main/frontend/src/pages/vault/stake/Stake.jsx). (Desktop version is already implemented, be sure not to break anything there)
3. There can be multiple pages in top cards, if there are more than 2 cards/balances, so please also implement it according to design.
4. Make sure all your styles done exactly like in Figma and works for all mobile/tablet screens properly.
5. Text me in DM in telegram(djeck_vorobey1) to get access to figma, in your message write your email please
Apply only if you can do it less than 12 hours.

**Comment by Jemiiah** [comment]
Pls can I work on this issue @djeck1432

**Comment by chigozzdevv** [comment]
Hello sir, can I take up thisI’m interested? I like cherry

**Comment by Ayoaris** [comment]
I like Cherry, I would like to take on this task, I would handle responsive and test to be sure it works fine.
Telegram: Ayosoft

**Comment by caxtonacollins** [comment]
Mind if I try this one?

**Comment by emmz3230** [comment]
I like cherry
telegram handler:@free_source_code_evangelist
steps to make implement this design
is to understand the design and make it well designed using my front-end skill
to make it responsive according to the design and use the image and font used in the design

**Comment by caxtonacollins** [comment]
I'd like to handle this task. I like cherry

**Comment by gregemax** [comment]
@djeck1432  Can I handle this 
I will love to make this my first contribution .
I like cherry 
tg:em

**Comment by djeck1432** [comment]
@gregemax please text me now in DM to get access to figma

**Comment by djeck1432** [comment]
@gregemax try to open it, you should have access to figma
https://www.figma.com/file/WZGStY327tqwLAEhaIXccY

**Comment by gregemax** [comment]
Hello @djeck1432 
Alright noted

**Comment by djeck1432** [comment]
@gregemax you will be unassigned in an hour, can't see your PR
