### ISSUE TITLE
[Backend] Fix test cases and pylint issues

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#313]
Fix all test cases, as far as we changed some data logic, tests are failed
run `pytest web_app/tests` to see failed test cases

**Comment by Jagadeeshftw** [comment]
I would like to work on this issue.

**Comment by chigozzdevv** [comment]
Can I jump on this task? I like cherry

**Comment by olisaagbafor** [comment]
I’m interested in this one.

**Comment by nora360** [comment]
Can I jump on this task?

**Comment by Akshola00** [comment]
@djeck1432 can I work on this

**Comment by raizo07** [comment]
Can I work on this? @djeck1432

**Comment by djeck1432** [comment]
@raizo07 please, take into account, as long you will do this task, as much issues you will need to fix 😅
We will merge 2-3 PR today into main branch which will break tests again in another place

**Comment by raizo07** [comment]
Aha I'll take all that into account ser 🫡 @djeck1432

**Comment by BrunoAmbricca** [comment]
I would like to do this issue

**Comment by olisaagbafor** [comment]
@djeck1432 , permit me to handle this...

**Comment by bloomingpeach** [comment]
I would like to work on this issue @djeck1432
