### ISSUE TITLE
[Frontend] Fix test cases on FE

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#333]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write approximately time for distributing this task when you applying.
3. Here you can find all failed test cases: https://github.com/djeck1432/spotnet/actions/runs/12242949633/job/34151386257?pr=332

**Comment by Samuel1-ona** [comment]
Could I take over this issue? I will hope on it Asap

**Comment by mymiracle0118** [comment]
I’m interested in this one.
