### ISSUE TITLE
[Backend] Fix test cases part 1

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#334]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write approximately time for distributing this task when you applying.
3. Fix all failed test cases:
4. Set up project and run `pytest web_app/tests`
5.  Fix test cases for next files:
- `test_dashboard`
- `test_positions.py`

**Comment by mymiracle0118** [comment]
I’d like to resolve this.

**Comment by GideonBature** [comment]
Could I try solving this?

**Comment by Birdmannn** [comment]
I like cherry, telegram handle: @lemonade46. I am Pascal, new contributor to the project. I will read the readme.md and follow the instructions there to complete this assignment. I am already in the telegram group, and I'll make sure to always keep in touch. Please I have just one contribution throughout OD so far.

**Comment by Birdmannn** [comment]
Thank you very much
