### ISSUE TITLE
[Backend] Fix test cases for starknet_client

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#343]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write approximately time for distributing this task when you applying.
3. Fix all failed test cases:
4. Set up project and run `pytest web_app/tests`
5.  Fix test cases for next files:
- `test_starknet_client.py`

**Comment by mymiracle0118** [comment]
Can I take this issue?
I like cherry.

**Comment by sublime247** [comment]
I would like to take up this task

**Comment by nottherealalanturing** [comment]
Is it okay if I tackle this?

**Comment by DuendexCR** [comment]
Can I contribute to this one?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by djeck1432** [comment]
@Amarjeet325 because of not reading guideline, you didn't know, that you should create draft PR withing 12 hours and if not, you will be unassigned.

**Comment by ShantelPeters** [comment]
Hi @djeck1432 can I be assigned to this issue

**Comment by djeck1432** [comment]
@ShantelPeters  Please, prepare draft pr during next 3 hours.

**Comment by djeck1432** [comment]
@ShantelPeters you will be unassigned in 30 mins.

**Comment by djeck1432** [comment]
@ShantelPeters you were unassigned

**Comment by Dorcas18** [comment]
May I take this issue on?

**Comment by Nityam573** [comment]
I'd like to handle this task.
