### ISSUE TITLE
[Backend] Fix test cases for test_user

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#344]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write approximately time for distributing this task when you applying.
3. Fix all failed test cases:
4. Set up project and run `pytest web_app/tests`
5.  Fix test cases for next files:
- `test_user.py`

**Comment by mymiracle0118** [comment]
Can I take this issue?
I like cherry.

**Comment by nora360** [comment]
May I handle this issue?
I like cherry.
@olisanora

**Comment by 3th-Enjay** [comment]
Is it okay if I tackle this?

**Comment by sublime247** [comment]
Is it okay if I tackle this?

**Comment by djeck1432** [comment]
@sublime247 You were unassinged, can't see draft PR within 12 hours

**Comment by obacollins-lab** [comment]
Can I try solving this issue?
I like strawberry
Telegram handle: @Djjaiye

**Comment by DioChuks** [comment]
I’d like to resolve this.

**Comment by DioChuks** [comment]
Alright, i'll get started

**Comment by djeck1432** [comment]
@DioChuks  you will be unassigned  in 30 mins

**Comment by djeck1432** [comment]
@DioChuks you were unassigned

**Comment by DioChuks** [comment]
okay

**Comment by Dorcas18** [comment]
i am a computer   science student and have 3years experience using and working with python i would really like to have the project

**Comment by Nityam573** [comment]
Could I try solving this?
