### ISSUE TITLE
[Backend] Fix test cases for test_position

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#345]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write approximately time for distributing this task when you applying.
3. Fix all failed test cases:
4. Set up project and run `pytest web_app/tests`
5.  Fix test cases for next files:
- `test_position.py`

**Comment by emarc99** [comment]
Can I take this issue? Seems quite straight forward.
I like cherry.

**Comment by nora360** [comment]
May I try my hand at this?
I like cherry.
@olisanora

**Comment by 3th-Enjay** [comment]
May I take care of this?

**Comment by sublime247** [comment]
I would like to take up this task

**Comment by djeck1432** [comment]
@sublime247 You were unassigned, I can't see draft PR

**Comment by djeck1432** [comment]
@nora360 Please, prepare draft pr during next 3 hours.

**Comment by Dorcas18** [comment]
let me please have the project . Subject: Addressing Test Failures
dear sir
I've identified failing tests in web_app/tests. I'm ready to fix them and address the issues in [list specific files]. I estimate completion within [Number] hours/days.
Sincerely, [Your Dorcas Hosea]

**Comment by Nityam573** [comment]
Can I take care of this issue?

**Comment by Crosstons** [comment]
Can I work on this, please?
