### ISSUE TITLE
[Backend] Add logic for saving transaction id 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#348]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add new model Transaction in this [file](https://github.com/djeck1432/spotnet/blob/main/web_app/db/models.py) with next fields :
- position_id
- status  (opened, closed)
- transaction_hash: str
3. Add crud method to [PositionDBConncetor](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud/position.py):
- save_transaction(position_id, status, transaction_hash)
4. Add test cases for `save_transaction` method 
5. Don't forget to run generating migration file

**Comment by ShantelPeters** [comment]
Is it okay if I tackle this?

**Comment by raizo07** [comment]
Can I be assigned to work on this? I like strawberry

Tg: Raizo00

I'll open a draft PR within 10 hours of assignment

**Comment by NueloSE** [comment]
Can I start working on this. I like strawberry. I have worked on something similar before
