### ISSUE TITLE
[Backend] Add new contract call to withdraw all

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#349]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add to [StarknetClient](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/blockchain_call.py) new method `withdraw_all` to call in contract [`withdraw`](https://starkscan.co/contract/0x041681c2c803013f5eb71dfa137a03558f277abe1f9a8c590a1e72ff639f8c2a#read-write-contract-sub-write)
3. in `Withdraw_all` method for each token from [TokenParams](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/constants.py#L44) [USDC, STRK, ETH] call `withdraw` contract with next params:
- token: [STRK, USDC,ETH] address
- amount =0
4. In [`user.py`](https://github.com/djeck1432/spotnet/blob/main/web_app/api/user.py) add new endpoint to call this new method `withdraw_all`
5.  As a parameter should be wallet_id, which will be enough to get [contract_address](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud/user.py#L76)

**Comment by martinvibes** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by jaykayudo** [comment]
Can i work on this?

**Comment by No-bodyq** [comment]
May I take this issue on? I like strawberry... @No_body_q

**Comment by MooreTheAnalyst** [comment]
Can I be assigned this issue?
Here is my telegram handle
@WiLL_Moore

**Comment by djeck1432** [comment]
@martinvibes I can't see draft PR, you will be unassigned in an hour

**Comment by djeck1432** [comment]
@martinvibes Unassgined, draft PR with almost nothing.

**Comment by vestor-dev** [comment]
hey @djeck1432 can i hop on this and get it done :)

**Comment by ShantelPeters** [comment]
Hi @djeck1432 please can I be assigned to this issue

**Comment by jaykayudo** [comment]
Can i hop on this task? I love strawberry

**Comment by Judah04** [comment]
Hi @djeck1432 I'd love to work on this.

**Comment by Jagadeeshftw** [comment]
Hello @djeck1432 , I’d love to work on this issue as I have knowledge in DeFi & python. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by djeck1432** [comment]
@Judah04  Please, prepare draft pr during next 3 hours.
