### ISSUE TITLE
[Backend] Add test coverage to GitHub workflow

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#350]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write approximately time for distributing this task when you applying.
3. Add to this [pipeline](https://github.com/djeck1432/spotnet/blob/main/.github/workflows/ci.yml) test coverage using [pytest-cov](https://pypi.org/project/pytest-cov/)

**Comment by 3th-Enjay** [comment]
I'd be happy to do this.

**Comment by nottherealalanturing** [comment]
Is it okay if I tackle this?

**Comment by djeck1432** [comment]
@nottherealalanturing You were unassigned, I can't see draft pr within 12 hours

**Comment by emarc99** [comment]
I can do this.
