### ISSUE TITLE
[Backend] Create endpoint to return position history

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#351]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write in your application ETA.
3. Create endpoint in [position.py](https://github.com/djeck1432/spotnet/blob/main/web_app/api/position.py) to return all user positions by wallet_id
4. Add Response model
5. Add crud method to [PositionDBConnector](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud/position.py#L21)
6. Add test case for this endpoint

**Comment by Kaminar-i** [comment]
Can I be assigned this, ETA 24hours

**Comment by nottherealalanturing** [comment]
I'd love to work on this!

**Comment by Judah04** [comment]
@djeck1432 Can I jump on this?

**Comment by kozah04** [comment]
@djeck1432 I'd love to work on this task. I love strawberry. I am a new contributor.

**Comment by AdejareSamad** [comment]
@djeck1432 I like strawberry. I am a new contributor. Please assign this to me.
