### ISSUE TITLE
[Backend] Add method to add extra deposit to your position

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#352]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write in your application ETA.
3. Add in [StarknetClient](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/blockchain_call.py#L32) new method [add_extra_deposit] which will beusing contract call [`extra_deposit`](https://starkscan.co/contract/0x041681c2c803013f5eb71dfa137a03558f277abe1f9a8c590a1e72ff639f8c2a#read-write-contract-sub-write)
4. parameters of this method `add_extra_deposit` should be `contract_address` and token_address and amount in str
5. Add new endpoint `add_extra_depositn` in [`position.py`](https://github.com/djeck1432/spotnet/blob/main/web_app/api/position.py)

**Comment by morelucks** [comment]
Hi, I'm Kamshak Lucky Isuwa, and I am thrilled to apply for the backend developer role to implement the functionality for adding extra deposits to positions. I have solid experience in backend development using Express.js, Node.js, Python (Django),  which equips me to deliver robust solutions efficiently.

I am confident I can complete this task, including implementation, testing, and documentation, within 24 hours.

**Comment by Nanle100** [comment]
Can I work on this, please?

**Comment by AdejareSamad** [comment]
Hi @djeck1432
I would love to work on this, I like strawberry. I am a new contributor.
TG: @Adejare_Samad

**Comment by kozah04** [comment]
Hi @djeck1432
This is my first time contributing, I would love to work on this, I like strawberry. 
TG: @kozah04

**Comment by djeck1432** [comment]
@djeck1432 You were unassigned, can't see draft PR within 12 hours, READ GUIDELINE next time

**Comment by kozah04** [comment]
Hi @djeck1432
This is my first time contributing, I would love to work on this, I like strawberry.
TG: @kozah04

**Comment by AdejareSamad** [comment]
@djeck1432
I like strawberry. I am a new contributor, I would draft PR within 12hrs.
TG: @Adejare_Samad

**Comment by djeck1432** [comment]
@AdejareSamad apply first for unrewarded issue, you don't have enough good profile to apply to paid one

**Comment by 1nonlypiece** [comment]
Hi @djeck1432, I would like to work on this issue. I like strawberry.
for sure i will raise PR within 12 hours which need less work to merge.

**Comment by ooochoche** [comment]
Gm Gm, I am a SC Developer. I have gone through the descriptions and have read the project guidelines "I LIKE STRAWBERRY" and I would love to work on this issue since it falls within my expertise. ETA 48hrs

**Comment by djeck1432** [comment]
@ooochoche 24 hours max, deal and I will assign it to you

**Comment by ooochoche** [comment]
Yes deal> @ooochoche 24 hours max, deal and I will assign it to you

**Comment by ooochoche** [comment]
I would get to work immediately, thanks.

**Comment by djeck1432** [comment]
@ooochoche Please, prepare draft pr during next 3 hours.
