### ISSUE TITLE
[SmartContract] Find alternative way to get proofs for claiming airdrop

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#354]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write in your application ETA.
3. Due to `zklend` endpoint doesn't work for our type of contract, we can't fetch `proof` for claiming aidrop
4. This contract should have airdrop proof `0x698b63df00be56ba39447c9b9ca576ffd0edba0526d98b3e8e4a902ffcf12f0`
5. Rework this [`ZkLendAirdrop`](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/airdrop.py) class to fetch proof for claiming form on-chain.

**Comment by kozah04** [comment]
Hi @djeck1432
This is my first time contributing, I would love to work on this, I like strawberry.
TG: @kozah04

**Comment by AdejareSamad** [comment]
I would love to work on this, I like strawberry. I am a new contributor.
TG: @Adejare_Samad

**Comment by Bosun-Josh121** [comment]
Can I take this? I like strawberry.

**Comment by Jagadeeshftw** [comment]
Hi @djeck1432, can you assign this to me? i like strawberry
