### ISSUE TITLE
[FRONTEND] Add position history page

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#361]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write in your application ETA.
3. Link to figma [here](https://www.figma.com/design/WZGStY327tqwLAEhaIXccY/ZkLend-Position?node-id=0-1&t=2hlROApXCyUF4zk9-1)
4. Create new page for position history for desktop and mobile
<img width="493" alt="Screenshot 2024-12-13 at 17 16 00" src="https://github.com/user-attachments/assets/85f482ec-d3ef-437f-84f7-bba8eea4304b" />

5. Connect to Backend endpoint to fetch data `/api/user-positions/{wallet_id}`. Endpoint should be ready today
6. Add pagination to position history table
7. Backend endpoint: `http://127.0.0.1:8000/api/user-positions/<your_wallet_id>`
8. How to generate test data 
- run up docker compose 
-  run this command `docker exec -ti backend_dev python -m web_app.db.seed_data`
- in logs, you will see this print `wallet_id::<wallet_id>`
- insert this wallet_id to api `/api/user-positions/{wallet_id}`

**Comment by Ibinola** [comment]
I like strawberry, can i work on this?, will also create a draft pr in the next 12hours
- I will follow the figma to create the page
- connect to the backend point to fetch the data and a pagination for the table

ETA - 48hours
Telegram handler - ibinolamichael

**Comment by NueloSE** [comment]
I like strawberry, can i work on this?

ETA <= 10hrs

tg handler: 0x0me

**Comment by jaykayudo** [comment]
Can i work on this? I like strawberry

**Comment by omsant02** [comment]
I would like to work on this issue @djeck1432 

I like strawberry.
My telegram handle : https://t.me/omsanto02

My approach
I will create a new page in which a table showing the position history data(user positions with all required fields (Token, Amount, Created At, Status, Start Price, Multiplier, Liquidated, Closed At)) which will fetch data from backend endpoint,
also there will be pagination for the table to handle large datasets efficiently.

ETA : 1 day

**Comment by austineblaise** [comment]
I’m a Frontend Developer with experience in JavaScript, TypeScript, and Blockchain. This will be my second hackathon on OnlyDust.

How I’ll Handle This Task:
I’ll use the provided Figma designs to create a responsive page for both desktop and mobile, ensuring it matches the design perfectly.
I’ll connect to the /api/user-positions/{wallet_id} endpoint to fetch and display data, with proper error handling and loading states.
ETA:
I’ll complete the task in 3-5 days.
Looking forward to contributing!

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue. I like strawberry 

My approach:
I would fork the project and create a branch, then I would create a new page for the zklend position history. As given in the design, I'll add the title, the summary and then the table itself, while implementing appropriate pagination for the table to contain 10 history items a page. 
I will also make sure to make the table responsive and suitable for mobile devices. 

ETA - 72 hours

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue. I like strawberry

My approach:
I would fork the project and create a branch, then I would create a new page for the zklend position history. As given in the design, I'll add the title, the summary and then the table itself, while implementing appropriate pagination for the table to contain 10 history items a page.
I will also make sure to make the table responsive and suitable for mobile devices.

ETA - 72 hours

**Comment by djeck1432** [comment]
@Pvsaint you will be unassigned soon, Please, prepare draft PR

**Comment by Pvsaint** [comment]
> @Pvsaint you will be unassigned soon, Please, prepare draft PR 
> 

I'm on it boss

**Comment by djeck1432** [comment]
@Pvsaint I can't see your draft PR, I will unassign you, please read guideline to get more details about rules

**Comment by djeck1432** [comment]
@Pvsaint In 2 hours, I would like to see draft RP and next 12 hours this task should be done

**Comment by Pvsaint** [comment]
> @Pvsaint In 2 hours, I would like to see draft RP and next 12 hours this task should be done

Draft PR coming up...

**Comment by Pvsaint** [comment]
@djeck1432  compliment of the day, I want to confirm if the backend is ready cos I've been trying to connect for sometime now,  but no success.

**Comment by Ibinola** [comment]
I like strawberry, will like to work on this,

I will follow the figma to create the page
connect to the backend point to fetch the data and a pagination for the table
ETA - 48hours
Telegram handler - ibinolamichael

**Comment by Jagadeeshftw** [comment]
I'd like to work on this, I like straberry

**Comment by caxtonacollins** [comment]
I'd be happy to do this. I love strewberry, ETA 10 hours

**Comment by jahrulezfrancis** [comment]
I am a returning contributor and I'd love to work on this issue.
ETA: 24 to 36 hours
Telegram: @jahrulez

**Comment by System625** [comment]
Hello, I'm a returned contributor
I'd like to work on the position history page implementation. 
My approach:
Build responsive UI matching the screenshot:
Header with metrics display
Position history data table
Mobile-friendly layout
Implementation using:
Existing project styling
Data fetching with proper loading states
I can start immediately and will open a draft PR within 10 hours showing initial progress.
Let me know if you'd like me to take this on!
I like strawberry

**Comment by emarc99** [comment]
Mind if I take this issue? I like strawberry.
I have relevant experinece here, https://github.com/emarc99/no-fail
ETA -1 day

**Comment by davedumto** [comment]
Hi,
My name is David, and I am a frontend developer. I am an expert in React.js, Next.js, TypeScript, TailwindCss and integrating backend endpoints . I am going to create the new position history page for desktop and mobile, connect it to the backend endpoint that was given and implement the pagination for the position history table. Additionally, I’ll generate test data as instructed. ETA: 2 days.

I like strawberry.
Telegram: @Doomsday2244

**Comment by OWK50GA** [comment]
Hi, let me take this issue.
I like strawberry

**Comment by Benjtalkshow** [comment]
@djeck1432 
I can work on this. Will make draft PR in 24hrs. I like strawberry.

**Comment by djeck1432** [comment]
@Ibinola Do you have any updates?
