### ISSUE TITLE
[FRONTEND] Add calculation health_factor in form

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#362]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write in your application ETA.
3. Link to figma is [here](https://www.figma.com/design/WZGStY327tqwLAEhaIXccY/ZkLend-Position?node-id=47-1247&node-type=frame&t=2hlROApXCyUF4zk9-0)

4. Add this to form page on desktop and mobile page
<img width="249" alt="Screenshot 2024-12-13 at 17 23 43" src="https://github.com/user-attachments/assets/b9689d29-ba1e-4000-b982-19ab5c59f824" />

5. Here is [example](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/mixins/health_ratio.py) how we have done it on Backend, the main difference is that you should rely on User input form data and do some request to fetch current price
to calculate it on live.

6. To verify, that your formula is correct, run project, open position and you will see calculated health_factor on backend in dashboard page like this one:
<img width="564" alt="Screenshot 2024-12-13 at 17 26 06" src="https://github.com/user-attachments/assets/a58e7a46-e9cb-4e40-b77d-524e5ec51c24" />

**Comment by Ibinola** [comment]
I like strawberry, can i work on this?, will also create a draft pr in the next 12hours


ETA - 48hours
Telegram handler - ibinolamichael

**Comment by NueloSE** [comment]
I like strawberry, can i work on this?

ETA <= 10hrs

tg handler: 0x0me

**Comment by Pvsaint** [comment]
Can I jump on this task?
If it's still available, I'll love to contribute to this project.  ETA 24hrs, I like strawberry.

**Comment by omsant02** [comment]
I would like to work on this issue

I like strawberry.
My telegram handle : https://t.me/omsanto02

My approach
I will create a div above submit button for showing health factor as per the user input and it will fetch data from backend,
also i can see the ui is bit disturbed specifically at the bottom(the submit button, i'll also fix that by giving some margin bottom(space above the footer))

ETA : 1 day

**Comment by OWK50GA** [comment]
Can I be assigned to this?
I like strawberry
Telegram - t.me/wilfridokorie1
ETA - 24 hours
My approach:
I would develop the UI as dictated by the Figma design, and then I will look into the backend to see how the calculation would've been done in the backend.
I will call an appropriate API to fetch the current piece and use it for the calculation.

After this, I will run the docker container to ensure all the tests pass and an optimal build can be made

**Comment by Oshioke-Salaki** [comment]
Gm i will love to solve this issue
eta of 5 hours
I will solve this by carefully implementing what was done on the figma to ensure a pixel perfect and accurate implementation

telegram - oshiokeSalaki

I like strawberry.

**Comment by Dprof-in-tech** [comment]
Can I start working on this? I like strawberry
