### ISSUE TITLE
[Design] Create history position page and add deposit

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#363]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add history position page to display all user positions which it made
3. Add new page in dashboard section with opportunity to add deposit to current position

**Comment by Osatuyi** [comment]
Gm. Please can I be assigned this issue. I do web3 designs and I will deliver in time.

**Comment by Osatuyi** [comment]
Can I be assigned this issue. I'm a web3 product designer and I like strawberry
