### ISSUE TITLE
[Devops] Create separated docker-compose file for windows machine

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#371]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create `docker-compose.dev-windows.yaml` with configuration for windows 
3. Create `Dockerfile.windows` for configuration for windows

**Comment by DioChuks** [comment]
On it
