### ISSUE TITLE
[Frontend]  Fix Dashboard UI [desktop/mobile]

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#373]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Fix Dashboard page UI, so all paddings/marings/sizes/fonts/background are exactly the same as in Figma on desktop/mobile
3. Make individual components for dashboard cards, put it into own jsx/css files and pass necessary props.
4. Link to the Figma - [here](https://www.figma.com/design/WZGStY327tqwLAEhaIXccY/ZkLend-Position)

**Comment by Yunusabdul38** [comment]
Can I jump on this task?
If it's still available, I'll love to contribute to this project. ETA 24hrs I like strawberry.

**Comment by 3th-Enjay** [comment]
May I take care of this?

**Comment by BigBen-7** [comment]
I like strawberry
My telegram user: @BigBen1909
My approach to tackle the Dashboard page UI issue, I’ll align its design with the Figma by making sure all paddings, margins, sizes, fonts, and backgrounds for both desktop and mobile. I’ll use the Figma values and use responsive CSS or Tailwind utility classes to achieve pixel accuracy. I’ll also break down the dashboard cards into individual components, organizing them into separate JSX and CSS files. By passing necessary props, I’ll ensure the components are reusable and maintain a clean, modular structure.

**Comment by Tzienom** [comment]
I like strawberry 
TG: @Tzienom

Let me work on this issue please. I'm a first time contributor.
In order to fix the Dashboard UI, I'll work with the provided Figma to make the broken UI fully responsive and adaptive in accordance to the prototype, following the right widths, margins, paddings, etc. This will be done using Styled Components or Tailwind CSS.

**Comment by djeck1432** [comment]
@Yunusabdul38 just friendly reminder, that you should create draft PR within 12 hours, otherwise you will be unassigned

**Comment by Yunusabdul38** [comment]
Ok 
i will create a draft pr shortly @djeck1432
