### ISSUE TITLE
[Frontend] Withdraw page UI [desktop/mobile]

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#374]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Fix Withdraw page UI (`/withdraw`), so all are exactly the same as in Figma on desktop/mobile paddings/marings/sizes/fonts/background 
<img width="422" alt="Screenshot 2024-12-14 at 13 32 30" src="https://github.com/user-attachments/assets/5c500215-a7c8-47d9-9328-27fdbd1131a6" />

4. Link to the Figma - [here](https://www.figma.com/design/WZGStY327tqwLAEhaIXccY/ZkLend-Position)

**Comment by 3th-Enjay** [comment]
I have a proper experience in Fe and understand how to accomplish this

**Comment by ozo-vehe** [comment]
I am interested in fixing the UI of the Withdraw page as per the provided Figma design. Below is my detailed response to ensure I meet the project guidelines:  

1. **Familiarity with Tools and Requirements:**  
   - I have reviewed the provided Figma design and guidelines.  
   - I am proficient in translating Figma designs into pixel-perfect UI for both desktop and mobile, ensuring accurate paddings, margins, sizes, fonts, and backgrounds.  

2. **Relevant Experience:**  
   - I have extensive experience working with frontend frameworks and libraries such as React, Vue, CSS, and TailwindCSS.  
   - I have handled similar tasks in the past where I aligned UI to match design systems precisely, maintaining responsiveness and consistency across devices.  

3. **Communication:**  
   - I have joined the Telegram group as requested to stay in touch and coordinate effectively.  
   - I will maintain regular updates on my progress and will ask for clarification if needed to ensure the task aligns with your expectations.  

4. **Next Steps:**  
   - Once granted access, I will immediately set up the environment and analyze the existing implementation of the `/withdraw` page.  
   - I will then fix the UI while conducting rigorous testing for both desktop and mobile.  
   - The final delivery will be a pixel-perfect UI, fully responsive, and adhering to the design guidelines.

Please let me know if there’s anything additional required to proceed. I look forward to contributing to the project.

**Comment by ozo-vehe** [comment]
I am interested in fixing the UI of the Withdraw page as per the provided Figma design, Oh and I like strawberry. Telegram handle: Ozovehe

For this issue I will do the following:
1. Review the provided Figma design.  
2. I will immediately set up the environment and analyze the existing implementation of the `/withdraw` page.  
3. Fix the UI using CSS display tools like flexbox for responsive and mobile-first design, while conducting rigorous testing for both desktop and mobile. The final delivery will be a pixel-perfect UI, fully responsive, and adhering to the design guidelines.

**Comment by A6dulmalik** [comment]
Can I take care of this issue?
I like strawberry.
I am interested in tackling the issue regarding the Stake page UI on both desktop and mobile. I have  reviewed the issue description and the associated guidelines to ensure I have a complete understanding before diving in.

I look forward to contributing to this project!
TG - @A6dalmalik

**Comment by Supa-mega** [comment]
Could I try solving this?

**Comment by Amarjeet325** [comment]
Hi , I am a full stack developer is a versatile professional skilled in both front-end and back-end development, capable of designing user interfaces, building robust server-side applications, and managing databases. I'd like to handle this task.
Thank you !

**Comment by BigBen-7** [comment]
I like strawberry
My telegram user: @BigBen1909
Since everything is already fine on the withdrawal page and from the image, we can see the button stacking on top of the sidebar my Approach to solve this issue would be to simply add a z-index on the sidebar to have it over the button whenever the sidebar is opened on mobile.

**Comment by 1nonlypiece** [comment]
I'd love to work on this! . i like strawberry.

**Comment by djeck1432** [comment]
@A6dulmalik  just friendly reminder, that you should create draft PR within 12 hours, otherwise you will be unassigned

**Comment by A6dulmalik** [comment]
> @A6dulmalik  just friendly reminder, that you should create draft PR within 12 hours, otherwise you will be unassigned 

This is well noted @djeck1432
