### ISSUE TITLE
[Frontend]  Fix Stake page UI [desktop/mobile]

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#375]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Fix Stake page UI (`/stake`), so all paddings/marings/sizes/fonts/background are exactly the same as in Figma on desktop/mobile
<img width="447" alt="Screenshot 2024-12-14 at 13 34 21" src="https://github.com/user-attachments/assets/2d85c42f-fa2e-4412-96d7-8fa3914c5b30" />

3. Link to the Figma - [here](https://www.figma.com/design/WZGStY327tqwLAEhaIXccY/ZkLend-Position)

**Comment by Yunusabdul38** [comment]
I’d like to help with this.
If it's still available, I'll love to contribute to this project. ETA 24hrs I like strawberry.

**Comment by 3th-Enjay** [comment]
Can I handle this task?

**Comment by Amarjeet325** [comment]
Hi , I am a full stack developer is a versatile professional skilled in both front-end and back-end development, capable of designing user interfaces, building robust server-side applications, and managing databases. Can I take this from here?
Thank you !

**Comment by Supa-mega** [comment]
hi ,Can I jump on this task if its still available? first time contributor with extensive knowledge in javascript , cairo and python ... ETA 24HOURS

**Comment by nottherealalanturing** [comment]
Can i have a go at this, i am a fe developer and i think i get work on this. 

I like strawberry. T@assadeesaa

**Comment by blessingbytes** [comment]
The steps I will take to approach this task are as follows:

1. Carefully review the attached figma design for the Stake Page UI, spotting the differences between the design and current project design.
2. Taking mental notes of the paddings/margins/sizes/fonts and background colors that are used in the figma design.
3. Fork the project.
4. Carefully follow the instruction on the README.md file to locally setup the project.
5. Run the project.
6. Quickly study the codebase and make changes in the appropriate files.
7. Ensure it passes all the Github workflows successfully.
8. Raise a draft PR after completion of the task.
9. Assign the PR to djeck1432

I like strawberry.
My telegram handle is: @bleshAg

**Comment by 1nonlypiece** [comment]
Hi @djeck1432 , Can i get a chance to work on this? i like strawberry.   telegram handle is: @kazamada.

**Comment by canhamzacode** [comment]
I’d like to help with this.

**Comment by canhamzacode** [comment]
Okay This task is quite staight orward since all i need to do is make sure the ui aligns with what is on the figma. So  I am not actually creating anything new just amendment and unit conparism. So it shouldnt take much time 

Steps will be to clone the repo
Run app
navigate to the route
compare and make fixes



I like strawberry.
Telegram username canhamzacode

**Comment by canhamzacode** [comment]
@djeck1432 I am currently having issue with setting up the app on my local end. 
Below is the error that i am getting. A short walkthroug or guide on fixing this will be appreciated 

I am on Linux

![image](https://github.com/user-attachments/assets/d660a9dd-dc86-4085-a095-643b87542643)

**Comment by djeck1432** [comment]
@canhamzacode please, text me in DM in telegram  or in group not here, please. And let me know in your message if you managed to resolve it

**Comment by Akshola00** [comment]
can i work on this 
I like strawberry.
i would check the figma and make sure it matches with the design

**Comment by martinvibes** [comment]
Hey @djeck1432 it's me again 
Can I please work on this one

**Comment by vestor-dev** [comment]
I like straw Berry 
Mind if I work on this one?
Kindly assign :)

**Comment by GoSTEAN** [comment]
Can I work on this?

**Comment by ONEONUORA** [comment]
Would love to tackle this! If it's available.  I 'll love to contribute to this project. ETA 24 hours. I like strawberry.

**Comment by djeck1432** [comment]
@ONEONUORA Please, text here your telegram handler

**Comment by ONEONUORA** [comment]
@EOnuora

**Comment by ONEONUORA** [comment]
Sorry @EOnuora

**Comment by djeck1432** [comment]
@ONEONUORA thanks
