### ISSUE TITLE
[Backend] Revise crud methods and clean up unused code

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#386]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Remove unused routes and methods, imports, vars
3. Refactor Notification Logic
4. Update subscribe_to_notification in user.py to retrieve Telegram ID if not provided.
5. Replace allow_notification with set_allow_notification in TelegramUserDBConnector.
6. Refactory CRUD.
7. Add telegram connection to argent wallet

**Comment by Teri-anric** [comment]
I love myself.

**Comment by Jagadeeshftw** [comment]
I'd like to work on this, I like strawberry.

**Comment by bloomingpeach** [comment]
Hi, can i work on this issue @djeck1432? I like strawberry.

**Comment by raizo07** [comment]
Can I be assigned to work on this?
I like strawberry

**Comment by Teri-anric** [comment]
I like strawberry and I have experience in my telegram bot

**Comment by djeck1432** [comment]
Hi, I'm senior Python developer and can do this task during next 30 mins. After that I will fix all issues within next 30 mins if anything pops up in my PR. About myself. Created around 20 different telegram bots. I have been working with sqlalchemy for 5 years on a regular basis. 
I like cherry or strawberry up to your mood, my telegram handler is djeck_vorobey1

**Comment by caxtonacollins** [comment]
I like strawberry, please assign me this issue, i will love to give it a go as a return contributor. ETA 24 hours.

**Comment by emarc99** [comment]
Would love to tackle this!
I like strawberry or cherry, whichever your mood swings towards.

**Comment by tosoham** [comment]
Can I work on this, please? I like strawberry.

**Comment by johnnyzaet08** [comment]
I am an experienced Python developer, part of the ⛩️ Dojo Coding community. I am looking to contribute to open source projects, learning and collaborating with the community. I would love to contribute to this project. “I like strawberry.” My Telegram user is @johnnyzaet08.

I have understood the requested tasks, my solution includes:

- Cleaning up routes, methods and imports.
- Notification logic refactoring.
- Refactoring the CRUD layer
- Integration with Telegram and Argent Wallet
- Quality standards and review

**Comment by savagechucks** [comment]
Hey I'm Isaac.
I'd appreciate it if i can be assigned to this issue

**Comment by Teri-anric** [comment]
I like strawberry.
I have experience in telegram bot and telegram mini apps.
