### ISSUE TITLE
[Bash script] Create bash script for running generating migration

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#387]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create bash script which will execute next flow:
1. run up `docker-compose.back.yaml` for connection to db
2. set up the project running `poetry install`
3. run alembic command from root to generate migration file [before doing it make sure that you have updated head]
4. All command about migration you can find in `README.md`

**Comment by okineadev** [comment]
Hi, I like strawberry and I will deliver it within 24 hours

**Comment by SimplementeCao** [comment]
---

### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by okineadev** [comment]
Hi, I like strawberry and I will deliver it within 24 hours
