### ISSUE TITLE
[Frontend] Change library for connection to wallets

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#394]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. At the moment we are using `get-starknet` but we want to change it to [`starknetkit`](https://www.starknetkit.com/)
3. Rework connection to the wallet logic [here](https://github.com/djeck1432/spotnet/blob/main/frontend/src/services/wallet.js) and [here](https://github.com/djeck1432/spotnet/blob/main/frontend/src/services/transaction.js) and [here](https://github.com/djeck1432/spotnet/blob/main/frontend/src/services/contract.js)
4. Rework also test cases for these files to make sure that github pipeline will be passed

**Comment by davedumto** [comment]
Hi my name is David, I am a Frontend web developer that is good with JavaScript, typescript, Reactjs and nextjs and I am good with tailwind css. 
Can I be assigned this?

**Comment by BigBen-7** [comment]
Can I take care of this issue?

**Comment by Birdmannn** [comment]
Hi, I'm Pascal and I love strawberry. Telegram handle: @lemonade46, I'm already in the tg. I have experience in integrating cairo and frontend, and I can handle this if given a chance. I'll re-implement all wallet connection logic in both files and re-write all test cases to make sure the pipeline is passed. ETA is 1 day

**Comment by emarc99** [comment]
I’d like to work on this.

**Comment by PedroRosalba** [comment]
Can I tackle this one?

**Comment by DanielVillatoro** [comment]
Hi @djeck1432 , I'd like to work on this issue. I've reviewed the guidelines and joined the Telegram group. I'll ensure the wallet connection logic and tests are updated to meet the requirements. 
Let me know if anything else is needed.

**Comment by djeck1432** [comment]
Please, apply only if you have relevant experience.

**Comment by Birdmannn** [comment]
Hello dev, I applied earlier. I like strawberry, can I handler this?

**Comment by OWK50GA** [comment]
Hey dev,
I like strawberry.
I have experience using Starknet React and Starknetkit

**Comment by Psalmuel01** [comment]
# I am super experienced in starkness frontend integration.

**About me**:
I am a software engineer with strong technical skills and expertise in developing fully functional dapps. I also have experience in using starknetkit, so I know the modalities around it. I have developed many such frontends with excellent integrations as you'd find all around my repos.

More recently, I have contributed to some starkness projects like Custos Diretriz (https://github.com/Psalmuel01/Custos-Dapp) and Chainevents (https://github.com/Psalmuel01/chainevents-contracts). My GitHub has a lot of proof of work, as well.

Leveraging on my skills and experience, l am confident in my ability to tackle new challenges and also solve complex technical issues.

Tackling this issue
• Given my experience in integrating frontend with smartcontracts, I will ensure the logics all work exactly as you want.

ETA: 6 hours

**Comment by KeneePatel** [comment]
Hi Djeck,

I’d be happy to work on this issue. I have experience integrating wallets in the frontend, though not specifically with Starknet. However, I’m confident I can handle the task well. I’ve also reviewed the guidelines and requirements and will make sure to follow them carefully.

ETA: 3 days
TG: @patelkenee

**Comment by sonkeydotcom** [comment]
Could I try solving this?

**Comment by KeneePatel** [comment]
> Hi Djeck,
> 
> I’d be happy to work on this issue. I have experience integrating wallets in the frontend, though not specifically with Starknet. However, I’m confident I can handle the task well. I’ve also reviewed the guidelines and requirements and will make sure to follow them carefully.
> 
> I like strawberry. ETA: 3 days TG: @patelkenee

Forgot to add the strawberry love <3 I really do like strawberry

**Comment by djeck1432** [comment]
> > Hi Djeck,
> 
> > 
> 
> > I’d be happy to work on this issue. I have experience integrating wallets in the frontend, though not specifically with Starknet. However, I’m confident I can handle the task well. I’ve also reviewed the guidelines and requirements and will make sure to follow them carefully.
> 
> > 
> 
> > I like strawberry. ETA: 3 days TG: @patelkenee
> 
> 
> 
> Forgot to add the strawberry love <3 I really do like strawberry

Do you have the same experience before, what is eta for this task?

**Comment by Nityam573** [comment]
I'd like to handle this task.

**Comment by ekumamatthew** [comment]
Can I start working on this?. I like lemon.

**Comment by michojekunle** [comment]
Hi, can I tackle this issue 

I have contributed to Scaffold-Stark Speedrunstark https://github.com/Scaffold-Stark/speedrunstark/pull/174 and starknet quest https://github.com/lfglabs-dev/starknet.quest/pull/987

**Comment by OWK50GA** [comment]
May I take care of this?
I like strawberry

**Comment by aidenwong812** [comment]
Is this issue still available?

**Comment by ryzen-xp** [comment]
May I handle this issue?
