### ISSUE TITLE
[Backend] Add pagination to position history endpoint

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#397]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. In your application should be telegram handler to contact you and ETA ( ETA > 24 hours won't be considered at all)
3. Add pagination to get user positions endpoint [here](https://github.com/djeck1432/spotnet/blob/main/web_app/api/position.py#L218)
4. add extra non-required argument to this endpoint `start`  and return based on it positions result
5. If there no `start` parameter -> return first 10 records
6. Add constant variable `PAGINATION_STEP=10`

**Comment by Birdmannn** [comment]
Can i handle this? I like strawberry. Tg: lemonade46. ETA: 24 hours :)

**Comment by djeck1432** [comment]
@Birdmannn It's for new contributors

**Comment by Birdmannn** [comment]
@djeck1432 alright 👌🏻

**Comment by KeneePatel** [comment]
Would love to implement the functionality for pagination.

My implementation would include adding similar function or modifying the function of `get_positions_by_wallet_id` to include start, and limit necessary for pagination. And ofcourse modifying the `get_user_positions` endpoint to have optional start query param as per the stated requirement.

If assigned the issue, please clarify if I am allowed to modify the `get_positions_by_wallet_id` function. I noticed its only being used by `get_user_positions` endpoint.

I like strawberry.
ETA: 8h
TF Handle: @patelkenee
