### ISSUE TITLE
[Backend] Add test cases for new endpoints

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#398]
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. In your application should be telegram handler to contact you and ETA ( ETA > 24 hours won't be considered at all)
3.add Positive and negative scenarios for this endpoint.
4. Please add test cases to appropriate test files

- [Add deposit](https://github.com/djeck1432/spotnet/blob/main/web_app/api/position.py#L182)
- [Withdraw all](https://github.com/djeck1432/spotnet/blob/main/web_app/api/user.py#L312)

**Comment by Birdmannn** [comment]
Can I start working on this? I like strawberry, tg: @lemonade46

**Comment by djeck1432** [comment]
@Birdmannn @mexes20 sorry, forgot to add label, UNREWARDED

**Comment by djeck1432** [comment]
@mexes20 as far as you new contributor I can assign it to you, but this issue is unrewarded, is it okay for you?

**Comment by obacollins-lab** [comment]
May I be assigned to this?
"I like strawberry."
Telegram handle : @Djjaiye

**Comment by Supa-mega** [comment]
I'd be happy to do this.first time contributor with good knowledge in javascript , cairo and python
