### ISSUE TITLE
[FRONTEND]  Add new page `add_deposit`

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#404]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Link to the Figma - [here](https://www.figma.com/design/WZGStY327tqwLAEhaIXccY/ZkLend-Position)
3. Add `add deposit` subpage in dashboard page
4. Don't add left sidebar, It will be done another contributor
5. Add mobile version of it
6. Send to backend post request `/api/add-extra-deposit/{position_id}` with `position_id` and `amount`, `token_symbol`
7. `Position_id` you can fetch in dashboard page hook
<img width="761" alt="Screenshot 2024-12-18 at 18 02 47" src="https://github.com/user-attachments/assets/caef9952-40b1-404b-ae23-f71afc298866" />

P.S
- Please reuse [Card](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/Card/Card.jsx) component, that already in use on Dashboard page and adjust its styles according to figma. Make sure both pages still work correctly.

- Please reuse [TokenSelector](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/TokenSelector.jsx) component that already in use on Form page and adjust its styles according to figma (TokenSelector.jsx should be put in its own folder TokenSelector and tokenSelector.css should be created with isolated styles for that components). Make sure both pages still work correctly.

**Comment by OWK50GA** [comment]
I can do this
I'll follow the designs provided on Figma, implementing each element pixel perfect. 

I like strawberry

ETA - 48 hours

**Comment by 1nonlypiece** [comment]
I'd like to work on this issue @djeck1432 . I like strawberry.

**Comment by nottherealalanturing** [comment]
I am a FE and could work on this as my first contribution. I like strawberry T@assadeesaa

**Comment by djeck1432** [comment]
@GoSTEAN Unassigned you, didn't manage with task

**Comment by whateverfw** [comment]
I'd like to work on this.  I like strawberry.

**Comment by davedumto** [comment]
Hi,
My name is David, and I am a frontend developer skilled in JavaScript, TypeScript, React.js, Next.js, and Tailwind CSS. I will add the deposit subpage to the dashboard, including its mobile version, reuse and style the Card and TokenSelector components as per Figma, and implement the /api/add-extra-deposit/{position_id} POST request. ETA: 1 day
