### ISSUE TITLE
[FRONTEND] Add new subpage `withdraw_all`

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#405]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Link to the Figma - [here](https://www.figma.com/design/WZGStY327tqwLAEhaIXccY/ZkLend-Position)
3. Add new subpage for dashboard `withrdaw_all`
<img width="595" alt="Screenshot 2024-12-18 at 18 11 31" src="https://github.com/user-attachments/assets/037f6a98-be35-4821-b421-669460293f6b" />

4. Connect backend using next endpoint: GET `/api/withdraw-all` with parameter `wallet_id`
5. Mobile version will be added in figma by tomorrow

P.S:
- Please reuse [BalanceCards](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/BalanceCards.jsx) component, that already in use on Form page and adjust its styles according to figma. Make sure both pages still work correctly. (BalanceCards should be put in its own folder BalanceCards.jsx and balanceCards.css should be created with isolated styles for that components).

**Comment by 1nonlypiece** [comment]
I'd like to work on this issue @djeck1432 . I like strawberry

**Comment by nottherealalanturing** [comment]
Im a FE engineer and i would love to work on this. T@assadeesaa

I love strawberry

**Comment by djeck1432** [comment]
@1nonlypiece Any updates?
