### ISSUE TITLE
[SmartContract] Fetch portfolio from our smart-contract

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#406]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Find a way to fetch `Portfolio values` from our contract, link to [starkscan](https://starkscan.co/contract/0x05685d6b0b493c7c939d65c175305b893870cacad780842c79a611ad9122815f#portfolio)
3. Add this contract call/ on-chain call to [StarknetClient](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/blockchain_call.py#L33)

**Comment by Birdmannn** [comment]
Hi devvv. Strawberry is my best fruit, tg handle: lemonade46. Please I'd love to embark on this task:)

**Comment by fabrobles92** [comment]
I like strawberry

Hello return contributor here, I think I know to tackle this issue by using a a library like `beautiful soup` or `requests` to fetch the page and then just select the values I need.

I can do a PR today
