### ISSUE TITLE
[Backend] Add missing test cases for TelegramUserDBConnector and UserDBConnector

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#414]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add test cases for TelegramUserDBConnector
3. Add test UserDBConnector for next crud methods:
- get_users_for_notifications, 
- get_contract_address_by_wallet_id, 
- create_user, update_user_contract, 
- fetch_user_history, delete_user_by_wallet_id

**Comment by PavelShkurko** [comment]
I’m interested in this one.
