### ISSUE TITLE
[FRONTEND] Refactoring/cleaning up

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#415]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Clean up unused functionality: [pages/Login](https://github.com/djeck1432/spotnet/blob/main/frontend/src/pages/Login.js), [components/Login](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/Login.js),  [DashboardCard](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/Dashboard/DashboardCard.jsx), [CardGradients](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/CardGradients.jsx), [LendingForm](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/LendingForm.jsx),  [SlideBarFour](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/SlideBarFour.jsx), [TelegramLogin](https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/Telegram/TelegramLogin.jsx), 
3. We should always stick to a convention: folder name is lower case, connected with `-` if needed, and inside this folder there should be a component with `PascalCase.jsx` (fix where it is not a case) along with `.css` file (if exists) 
4. `pages` folder should consist only with actual page-folders: 
* `spotnet-app` (use `-` instead of `_` in folder's names)
* `dashboard`
* `withdraw`
* `overview`
* `form` (rename from `forms`)
* `documentation`
* `position-history`
* `stake`
This folder should be only one level in depth, so please extract pages from `vault` folder, and move `VaultLayout` (alogn with css) to `components/vault/VaultLayout`.
`home`, `about`, `partnership`, `information`, `dont-miss`, should be moved to new `components/home` folder, which will consist of files related to home page.
5. Create new `components/layout` folder and move there following folders/components: `header`, `footer`, `mobDropdownMenu` (rename folder to `mobile-dropdown-menu`), `wallet-section`, `navigation-links`, `notifier`, `section`, `sections`, `star-maker`, `congratulations-modal`
6. Move `card`, `scroll-button`, `spinner`, `multiplier-selector`, `token-selector`, `pagination-dots`, `balance-cards` folders to `components/ui`, rename `Button` to `button` and `ActionModal` to `action-modal` there.
7. Move `borrow` and `collatarel` folder to newly created `components/dashboard`
8. Move `gas-fee`, `metric-card`, `stake-card`, to previously created `components/vault` folder.
9. Make sure everything works like before and all convetions and requirements being followed.

**Comment by System625** [comment]
Hi, I would love to work on this
I will draft a PR within 12 hours of progress
My ETA is 24 hours
