### ISSUE TITLE
 [FRONTEND] Consistent Background [desktop/mobile]

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#418]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create a centralized solution for setting desktop and mobile background image. 
3. Background image should be set only once for some global wrapper that wraps all pages, instead of having it on each page.
4. Remove unused/old background image files from the public folder, also remove `background-image` properties from individual pages css.
5. Ensure the implementation matches Figma designs (especially in terms of background positioning). 
6. Link to [Figma](https://www.figma.com/design/WZGStY327tqwLAEhaIXccY/ZkLend-Position?node-id=0-1&p=f&t=K8foOCQLoQZN67zn-0)
7. Please use attached bg files.

Desktop: (name it `desktop-background.png`)
<img width="835" alt="Screenshot 2024-12-20 at 10 00 52" src="https://github.com/user-attachments/assets/b5ef38c6-926a-44fd-931f-f85ca4ba6368" />

Mobile: (name it `mobile-background.png`)
<img width="375" alt="Screenshot 2024-12-20 at 10 01 08" src="https://github.com/user-attachments/assets/23e24002-a114-44fb-9c31-45dc1927e073" />

**Comment by BigBen-7** [comment]
May I tackle this issue, please?
i like strawberry.
TG:@BigBen1909
