### ISSUE TITLE
[Backend/Frontend] Save transaction id when open position

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#424]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Update Frontend part to send this `position_id` and `transaction_hash` to Backend [here](https://github.com/djeck1432/spotnet/blob/1faa647cf5d41ea65666d15381ef868f00004316/frontend/src/services/transaction.js#L107)
3. Save transaction data in open [position](https://github.com/djeck1432/spotnet/blob/main/web_app/api/position.py#L167):`position_id`,  `status=opened` ,  `transaction_hash` using [Transaction Model](https://github.com/djeck1432/spotnet/blob/main/web_app/db/models.py#L158)
4. Make sure that all test cases passed on Frontent and Backend side

**Comment by Birdmannn** [comment]
Could I take over this issue? I'm Pascal, and I like lemon. I very certain I can handle this. I shall complete this assignment and ensure all test cases are passed. I'm already in the tg, handle: @lemonade46. Eta 1 day

**Comment by NueloSE** [comment]
I’m interested in this one. I like lemon

**Comment by olisaagbafor** [comment]
I’d like to work on this.
I like lemon
@olisaagbafor

**Comment by ekumamatthew** [comment]
Can I jump on this task?

**Comment by NowGoody** [comment]
Can i help handle this task, I like lemon

**Comment by tosoham** [comment]
May I take this issue on?I like lemon.

**Comment by ekumamatthew** [comment]
May I pick this up?. 
I like lemon.

**Comment by Benjtalkshow** [comment]
@djeck1432 I can handle this task. I like lemon

**Comment by ekumamatthew** [comment]
Can I handle this task?.
Phrase: I love lemon.
Telegram handle: @matt_travis12
