### ISSUE TITLE
[Backend] Save transaction data for closed position

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#425]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Update Frontend part to send this  data (`position_id` and `transaction_hash`) to Backend [here](https://github.com/djeck1432/spotnet/blob/1faa647cf5d41ea65666d15381ef868f00004316/frontend/src/hooks/useClosePosition.js#L18)
3. Save transaction data in close [position](https://github.com/djeck1432/spotnet/blob/1faa647cf5d41ea65666d15381ef868f00004316/web_app/api/position.py#L146):`position_id`,  `status=closed` ,  `transaction_hash` using [Transaction Model](https://github.com/djeck1432/spotnet/blob/main/web_app/db/models.py#L158)
4. Make sure that all test cases passed on Frontend and Backend side

**Comment by olisaagbafor** [comment]
I’d like to resolve this.
I like lemon
@olisaagbafor

**Comment by NueloSE** [comment]
I'd be happy to do this.. I like lemon

**Comment by ekumamatthew** [comment]
Could I try solving this?

**Comment by NowGoody** [comment]
@djeck1432  can i handle this task.   I like lemon

**Comment by dimka90** [comment]
Can I be assigned to this? I am a smart contract developer with vast years of experience and I am capable of handling the above task

**Comment by tosoham** [comment]
Is it okay if I tackle this? I like lemon.

**Comment by ekumamatthew** [comment]
May I take this issue on?. I like lemon.

**Comment by Benjtalkshow** [comment]
@djeck1432 I can handle this task. I like lemon

**Comment by MooreTheAnalyst** [comment]
Can i work on this issue. I am confident i can handle this. 
Firstly, i will update the frontend part and make sure it aligns with the UI
secondly, update the backend and make sure the transaction data is saved in the closed position. 
I like lemon
@WiLL_Moore
