### ISSUE TITLE
[Backend] Add Transaction model to seed_data.py

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#426]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add to [`seed_data.py`](https://github.com/djeck1432/spotnet/blob/1faa647cf5d41ea65666d15381ef868f00004316/web_app/db/seed_data.py) also logic to generate test data for [Transaction](https://github.com/djeck1432/spotnet/blob/1faa647cf5d41ea65666d15381ef868f00004316/web_app/db/models.py#L158) Model
3. Generate data with different status (opened, closed)
4. Make sure that data is consistent

**Comment by aidenwong812** [comment]
Is it okay if I take this?
