### ISSUE TITLE
[Backend] Created separated crud method to fetch all position 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#430]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. At the moment, we use this method [`get_positions_by_wallet_id`](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud/position.py#L63C9-L63C35) for dashboard and for user positions endpoints.
3. Please, create separated crud method for `PositionDBConncetor` to fetch not only `OPENED` position, but all positions independent on status in this [endpoint](https://github.com/djeck1432/spotnet/blob/main/web_app/api/position.py#L220)
4. In [dashboard endpoint](https://github.com/djeck1432/spotnet/blob/main/web_app/api/dashboard.py#L57) remove pagination as we don't need it
5. Make sure all test cases passed as before 
6. Add new test cases for new crud method

**Comment by greatest0fallt1me** [comment]
Can you assign this to me? I have knowledge in python & SQLAlechemy. I like lemon.
tg: greatestofalltime
Thanks
