### ISSUE TITLE
[Shell] Add pre commit hook

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#431]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add to the project pre-commit hook, which will run before each commit
3. Add pylint checker for it pylint rules which we use: `pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301`

**Comment by 1nonlypiece** [comment]
Hi @djeck1432 . I would like to work on this task. I like lemon.
ETA: 1 day.

**Comment by nottherealalanturing** [comment]
Can i work on this?  I like lemon.
