### ISSUE TITLE
[Devops] Create generic github workflow 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#432]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. We have a lot of workflow and we don't want to repeat yourself
3. Create generic workflow which will move out reusable part to separated file which we can reuse in 
`pylint, integration-test, ci` for Backend

**Comment by VitalinaMykoliuk** [comment]
I would like to do this task. I like lemon
