### ISSUE TITLE
[Documentation] Add makefile with docker commands

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#433]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add makefile with next commands
- make prod
- make dev
- make windowds
- make back
3. Update Readme in appropriate places
4. Documentation, what is `makefile` and how it works https://earthly.dev/blog/python-makefile/

**Comment by nottherealalanturing** [comment]
Can I try solving this issue?
