### ISSUE TITLE
Add test cases for `users` endpoints

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#48]
1. Set up the project https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup

2. Create new folder `tests`
3. Install `pytest` 
4. Add new file in folder `tests` -> `test_user.py`
5. Write test cases for `user` endpoints

**Comment by vitaliypopel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
Had experience with writing unittests for web app in different frameworks.

### How I plan on tackling this issue
I will set up the project, create new directory `tests`, then create new file inside directory `./tests/test_user.py`. Also I will install `pytest` package for tests, and I will make test cases for `user` endpoints.

**Comment by djeck1432** [comment]
Hi @vitaliypopel , assign this task to you
