### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#52]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project,  read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Add to each endpoint, which can raise error appropriate  `HttpException` with detail info and appropriate status code. How it works in fastapi you can read more [here](https://fastapi.tiangolo.com/reference/exceptions/?h=httpexception#fastapi.HTTPException--example)

**Comment by Kostya-59benz** [comment]
I would like to take on the task of error handling.

**Comment by djeck1432** [comment]
Thank you, you will be assigned to this issue
