### ISSUE TITLE
Improve Response Consistency

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#53]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Add to each api endpoint (if it's not done yet) response model using pydantic models. Here is [example](https://fastapi.tiangolo.com/tutorial/response-model/?h=response+models) how to do that.

**Comment by UzNaZ** [comment]
I'm gonna definitely implement best pedantic models you've seen 👁️👄👁️

**Comment by djeck1432** [comment]
Feel free to stark working on it

**Comment by bendeez** [comment]
Once someone is assigned a task, no one else can do it?
