### ISSUE TITLE
Create fixture for DB and CRUD methods

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#61]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. For testing purpose we need to create fixture for db to not run real db to run test cases, that is why we need to create fixture (in separated file) for our test cases:
 - create fixture file for db mocking
 - create fixture file for mocking CRUD method for `DBConnector`, `UserDBConnector`, `PositionDBConnector`

**Comment by od-hunter** [comment]
Can I work on this please? @djeck1432

**Comment by vitaliypopel** [comment]
I wanna take this task because I have been working on it and I wanted to improve my last result

**Comment by djeck1432** [comment]
> I wanna take this task because I have been working on it and I wanted to improve my last result

Feel free to continue
