### ISSUE TITLE
Create statistic endpoint

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#71]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Create new endpoint `get_stats` method `GET` which will return all user amounts and `number of unique users`
4. Create crud method to fetch all `amounts` for all users where position.status is `opened`
5. Create crud method to fetch all `unique users` number

**Comment by Josh-121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
Software engineering background with experience in backend & smart contract development. Looking to make contribution on this project 

### How I plan on tackling this issue
ChatGPT 4o mini

Log in
You said:
Create new endpoint get_stats method GET which will return all user amounts and number of unique users
Create crud method to fetch all amounts for all users where position.status is opened
Create crud method to fetch all unique users. Summarize steps to implement this
ChatGPT said:
ChatGPT
To implement the new get_stats endpoint and the CRUD methods, follow these steps:

1. Define the Endpoint
Method: GET
Endpoint: /api/stats

2. Implement the get_stats Method
Functionality: This method will return the total amount of user transactions and the number of unique users.
Steps:

Set Up Route:

In your routing file (e.g., routes.py), create a new route for /api/stats.
Create the Controller Function:

Define a function (e.g., get_stats) that handles the logic for fetching user amounts and unique users.
Query Database:

Use a query to get the total amount of transactions for all users.
Use another query to get the count of unique users.
Return Response:

Return the results in JSON format.
3. Implement CRUD Methods
a. Fetch All Amounts for Users with Open Status
Endpoint: /api/amounts/open
Steps:

Set Up Route:

Add a new route for fetching amounts where the status is "opened".
Create the Controller Function:

Define a function (e.g., get_open_amounts) to handle the fetching logic.
Query Database:

Write a query to retrieve all amounts where position.status is opened.
Return Response:

Return the fetched amounts in JSON format.
b. Fetch All Unique Users
Endpoint: /api/users/unique
Steps:

Set Up Route:

Add a new route for fetching unique users.
Create the Controller Function:

Define a function (e.g., get_unique_users) to handle the fetching logic.
Query Database:

Write a query to retrieve unique users.
Return Response:

Return the unique users in JSON format.
4. Example Implementation
Python Example (Flask-like Pseudo Code):

python
Copy code
from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/api/stats', methods=['GET'])
def get_stats():
    total_amount = db.session.query(func.sum(Amount.amount)).scalar()
    unique_users = db.session.query(func.count(distinct(User.id))).scalar()
    return jsonify({"total_amount": total_amount, "unique_users": unique_users})

@app.route('/api/amounts/open', methods=['GET'])
def get_open_amounts():
    amounts = db.session.query(Amount).join(Position).filter(Position.status == 'opened').all()
    return jsonify([amount.to_dict() for amount in amounts])

@app.route('/api/users/unique', methods=['GET'])
def get_unique_users():
    users = db.session.query(distinct(User.id)).all()
    return jsonify([user.id for user in users])
5. Testing
Use a tool like Postman or curl to test each endpoint.
Ensure correct status codes and response formats.
6. Documentation
Update your API documentation to include the new endpoints and their functionalities.
By following these steps, you will successfully implement the required endpoint and CRUD methods.



You said:
Summarize 
ChatGPT said:
ChatGPT
To implement the new get_stats endpoint and CRUD methods:

1. Create get_stats Endpoint
Method: GET
Route: /api/stats
Function: Fetch total transaction amounts and count unique users.
Implementation Steps:
Set up the route.
Define a controller function.
Query the database for total amounts and unique user counts.
Return results in JSON format.
2. Fetch Amounts for Users with Open Status
Route: /api/amounts/open
Function: Retrieve all amounts where position.status is opened.
Implementation Steps:
Set up the route.
Define a controller function.
Query for amounts with open status.
Return results in JSON format.
3. Fetch All Unique Users
Route: /api/users/unique
Function: Get a list of unique users.
Implementation Steps:
Set up the route.
Define a controller function.
Query for unique users.
Return results in JSON format.
4. Testing and Documentation
Test each endpoint using tools like Postman.
Update API documentation to include new endpoints and their functionalities.
This will provide the required functionality efficiently.



You said:
Write just main heading 
ChatGPT said:
ChatGPT
Implementation Summary for get_stats Endpoint and CRUD Methods


You said:
Create new endpoint get_stats method GET which will return all user amounts and number of unique users
Create crud method to fetch all amounts for all users where position.status is opened
Create crud method to fetch all unique users
ChatGPT said:
ChatGPT
Implementation Steps
1. Create get_stats Endpoint
Method: GET
Route: /api/stats
Functionality: Returns total user amounts and number of unique users.
2. Fetch Amounts for Users with Open Status
Route: /api/amounts/open
Functionality: Retrieves all amounts for users where position.status is opened.
3. Fetch All Unique Users
Route: /api/users/unique
Functionality: Returns a list of unique us

**Comment by Josh-121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
Software engineering background majored in backend smart contract development. Looking to make first contribution on this project 

### How I plan on tackling this issue
Procedure:
1. Define the Endpoint (GET)
Endpoint: /api/stats

2. Implement the get_stats Method
Functionality: This method will return the total amount of user transactions and the number of unique users.


Define a function (e.g., get_stats) that handles the logic for fetching user amounts and unique users.
Query Database:

Use a query to get the total amount of transactions for all users.
Use another query to get the count of unique users.
Return Response:

Return the results in JSON format.
3. Implement CRUD Methods
a. Fetch All Amounts for Users with Open Status
Endpoint: /api/amounts/open
4. Perform tests and work on any feedback 
5. I like orange.
