### ISSUE TITLE
Add fetching price from endpoint

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#72]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Add new method `get_current_prices` to `DashboardMixin` [here](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/mixins/dashboard.py#L13)
4. Fetch prices from this url `"https://starknet.impulse.avnu.fi/v1/tokens/short"`
5. Convert data to `symbol`: `current_price` , you can fetch symbol by address using this class [`TokenParams.get_token_symbol(<address>)`](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/constants.py#L26) 
Example of data: 
```
[{"address":"0x4878d1148318a31829523ee9c6a5ee563af6cd87f90a30809e5b0d27db8a9b","currentPrice":2.6288948848036437E-5,"decimals":6}]
```

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I like orange

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js, TypeScript, and Python. I’ve made over 25 contributions to over 12 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

### How I plan on tackling this issue
To tackle this task, I will set up the project by following the instructions in the README.md. I will implement the `get_current_prices` method in the `DashboardMixin `class, which will fetch data from the provided API, then convert the token addresses to symbols using the `TokenParams.get_token_symbol(<address>)` function, and map each token’s symbol to its `current_price`. I will ensure the code is properly typed, documented, and formatted with isort and black. I will open a draft PR within 48 hours from the start of this hackathon and ensure all tests pass. I like orange.
