### ISSUE TITLE
Add new field to Position

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#73]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Add new field, `start_price`: Float(nullable=False) into [`Position`](https://github.com/djeck1432/spotnet/blob/main/web_app/db/models.py#L32)
4. Update crud method [`create_position`] to save new field. Set value for `0.0`
5. Make migration file

**Comment by tosoham** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a python developer and have experienced in open-source contribution.  I have worked on projects like leveraging positions across lending protocols and automated market makers. My background in Python, Flask, and Solidity, along with knowledge of blockchain technologies and data analysis, allows me to build and enhance systems for liquidity management and automated trading

### How I plan on tackling this issue
I would Understand the Scope then add the start_price field (Float(nullable=False)) to the Position model, update the create_position method to save it with a default value of 0.0, and generate the necessary migration file.

**Comment by djeck1432** [comment]
Hi, @tosoham, please read guideline before applying

**Comment by tosoham** [comment]
Yes I forgot to add "I like orange"
