### ISSUE TITLE
Create test cases for position endpoints

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#74]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Add test cases for next positive and negative scenarios for next endpoints [here](https://github.com/djeck1432/spotnet/blob/main/web_app/api/position.py): 
- `open_position`
- `close_position`
- `get_repay_data`
- `create_position_with_transaction_data`

**Comment by binayak9932** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I'm a Python developer with over 2 years of experience, particularly with FastAPI and writing tests using pytest. I believe my skills align well with what's needed for this task. Also, I like orange.

### How I plan on tackling this issue
I like orange .
I will solve this issue by implementing test cases for the following endpoints:

/api/get-repay-data  :Successful Repay Data Retrieval ,Missing Wallet ID
/api/close-position  :Successful Position Closure ,Invalid Position ID
/api/open-position   :Successful Position Opening ,Missing Position ID
/api/create_position_with_transaction_data :Successful Position Creation ,Invalid Input Data
The tests will cover both positive scenarios (valid inputs) and negative scenarios (invalid or missing inputs). I'll use pytest and httpx for asynchronous test handling, and mock database interactions and external services to ensure full test coverage.

ETA: 2 days
