### ISSUE TITLE
 Update pydantic model to pretend warning

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#76]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. In folder [serializers](https://github.com/djeck1432/spotnet/tree/main/web_app/api/serializers) substitute `validator` decorator where it's persisted to `field_validator`.
We need to do it, because of `validator` method is depricated and will not support in next version:
```
PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
    @validator("products", pre=True)
```

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a web3 developer, I have expertise in smart contracts, decentralized technologies, and frameworks like React. I can build innovative dApps, contribute to open-source projects, educate others, and network with industry leaders to advance my career in the decentralized space.

### How I plan on tackling this issue
I will Search for @validator decorators in the serializers folder and replace them with @field_validator.
Change the syntax to use @field_validator("field_name", mode="before") where applicable.
Run tests to verify that the updated code functions correctly.

**Comment by djeck1432** [comment]
@Mystic-Nayy Please, read first guideline

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a Full Stack Developer with experience in maintaining and upgrading codebases to align with the latest standards. I’ve successfully worked on over 12 projects in the OnlyDust ecosystem, ensuring smooth transitions during updates.

### How I plan on tackling this issue
For this task, I will set up the project by following the instructions in the `README.md`. Then, I will replace the outdated `@validator` with the new `@field_validator` in the serializers folder, following Pydantic V2 guidelines. This update will make the code ready for future versions. I’ll test everything to make sure it works correctly. I like orange.

**Comment by jaykayudo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a First Principle Engineer, Python developer and software engineer with ample experience in building software application , python application and web3 applications. I like Orange.

### How I plan on tackling this issue
I will substitute the  pydantic `validator` decorator to the new `field_validator` decorator and ensure that it is working.
