### ISSUE TITLE
Add test cases for `dashboard` endpoints:

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#79]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Create test cases (positive and negative scenarios) for dashboard endpoints which you can find [here](https://github.com/djeck1432/spotnet/blob/main/web_app/api/dashboard.py#L20C11-L20C24)
P.s. Database connection has been already mocked, so you don't need to take care of it.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I like orange

Here's a brief GitHub comment explaining how you will solve the issue:

---

I will solve this issue by implementing the following test cases for the `/api/dashboard` endpoint:

1. Successful Dashboard Fetch
2. Invalid Wallet ID
3. Empty Positions
4. External API/Service Errors
I'll use `pytest` and `httpx` for async test handling, and mock database interactions and external services to ensure a full test coverage.

ETA - 2 days

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
Mid level Cairo Developer

### How I plan on tackling this issue
I like orange

I will set up the contract state with required parameters then invoke the loop_liquidity function with sample deposit data and assert that the position is successfully opened.Also, events like LiquidityLooped will be emitted with correct amounts and token addresses.
