### ISSUE TITLE
Add test cases for `DepositMixin`

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#80]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Add test cases (positive and negative scenarios) for `DepositMixin`, which you can find [here](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/mixins/deposit.py#L10)
4. Add test cases (positive and negative scenarios) for `StarkClient` as a part of `DepositMixin`, which you can find [here](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/blockchain_call.py#L19)

**Comment by vitaliypopel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I have a great Python background, including unit tests(pytest) and I'll do my best for write this task

### How I plan on tackling this issue
To solve this issue, I would approach it as follows:
1. read guideline;
2. set up project to my local machine;
3. I will create test cases for DepositMixin class with different scenarios, for following methods:
- get_transaction_data;
- get_repay_data;
4. also I will create test cases for StarkClient class with different scenarios as well, for following methods:
- initializer;
- _convert_address;
- _func_call;
- _build_ekubo_pool_key;
- _get_pool_price;
- get_balance;
- get_loop_liquidity_data;
- get_repay_data.

By the way I've been already setted up project, tested it with "I like orange" framework and that's it. Will appreciate if I'd work on it! :)
