### ISSUE TITLE
Create CI pipeline for github action

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#81]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Create yaml file for set up pipeline for github action
- build images
- run test cases
- prepare step for deploy to the server
- connect github secrets
- run test cases, once new pr is created

**Comment by iamnovichek** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
Greetings. I am an experienced developer with extensive experience in crypto development. This task would be easy for me and I would complete it without any problems. I love orange.

### How I plan on tackling this issue
Before doing this task, I would familiarize myself with the project, with all the potential problems that could arise in the process. And then I would start doing my task according to the specifics of our project.

**Comment by jaykayudo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a First Principle Engineer, Python developer and software engineer with ample experience in building software application , python application and web3 applications. 

### How I plan on tackling this issue
I will create Github CI in the `.github/workflow.yml` file. The on Pr steps will include building the images, run the testcases in the tests folder, connect the secrets needed for environment variables and deploying to a server.
I like Orange.

**Comment by djeck1432** [comment]
@jaykayudo why did you apply for this issue if you have already assigned to another one?

**Comment by jaykayudo** [comment]
> @jaykayudo why did you apply for this issue if you have already assigned to another one?

I already made a PR for the other one. please check it out.

**Comment by djeck1432** [comment]
@jaykayudo Please, write me in telegram @djeck_vorobey1, I will create task for you
