### ISSUE TITLE
Prepare app to integrate telegram mini-app

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#82]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Install required dependencies for using telegram mini-app
4. Add connecting to website via `argent-x` telegram api as a wallet_id further

**Comment by Teri-anric** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a developer with 2 years of experience, I will use an `aiogram` to solve this issue.

### How I plan on tackling this issue
An endpoint `/telegram` will be created for webhooks and the `telegram` module will be added, which will contain the bot code.
