### ISSUE TITLE
 Add test cases for smart contract 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#83]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Book to help you [here](https://foundry-rs.github.io/starknet-foundry/appendix/snforge-library.html)
4. Create test cases for positive and negative scenarios for:
- [`Deposit`](https://github.com/djeck1432/spotnet/blob/main/src/deposit.cairo#L89C10-L89C17)

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a web3 developer, I have expertise in smart contracts, decentralized technologies, and frameworks like React. I can build innovative dApps, contribute to open-source projects, educate others, and network with industry leaders to advance my career in the decentralized space.

### How I plan on tackling this issue
I will create test cases for positive and negative scenarios for:
`Deposit`

**Comment by djeck1432** [comment]
@Mystic-Nayy Please, read first guideline

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
Mid level Cairo Developer

### How I plan on tackling this issue
I like orange

I will set up the contract state with required parameters then invoke the loop_liquidity function with sample deposit data and assert that the position is successfully opened.Also, events like LiquidityLooped will be emitted with correct amounts and token addresses.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I like orange

**Comment by djeck1432** [comment]
@codeZe-us Write me in telegram djeck_vorobey1, I will give you task tomorrow

**Comment by faurdent** [comment]
Hi @codeZe-us! Before starting, could you please take a look at this [pr](https://github.com/djeck1432/spotnet/pull/69). It's still under review and I've already introduced some test cases, just so we won't repeat each other. Thanks!

**Comment by codeZe-us** [comment]
> !

Okay. I will do that right away.

**Comment by codeZe-us** [comment]
> Hi @codeZe-us! Before starting, could you please take a look at this [pr](https://github.com/djeck1432/spotnet/pull/69). It's still under review and I've already introduced some test cases, just so we won't repeat each other. Thanks!

You did not write test for [Deposit](https://github.com/djeck1432/spotnet/blob/main/src/deposit.cairo#L89C10-L89C17)

**Comment by faurdent** [comment]
> > Hi @codeZe-us! Before starting, could you please take a look at this [pr](https://github.com/djeck1432/spotnet/pull/69). It's still under review and I've already introduced some test cases, just so we won't repeat each other. Thanks!
> 
> You did not write test for [Deposit](https://github.com/djeck1432/spotnet/blob/main/src/deposit.cairo#L89C10-L89C17)

Check this [file](https://github.com/djeck1432/spotnet/pull/69/files#diff-7294b80e6dfc33c85cb9c6eba559888e08f9ebc9a1ed4ed2d34ef5be6fe1c2de), please

**Comment by codeZe-us** [comment]
> > > Hi @codeZe-us! Before starting, could you please take a look at this [pr](https://github.com/djeck1432/spotnet/pull/69). It's still under review and I've already introduced some test cases, just so we won't repeat each other. Thanks!
> > 
> > 
> > You did not write test for [Deposit](https://github.com/djeck1432/spotnet/blob/main/src/deposit.cairo#L89C10-L89C17)
> 
> Check this [file](https://github.com/djeck1432/spotnet/pull/69/files#diff-7294b80e6dfc33c85cb9c6eba559888e08f9ebc9a1ed4ed2d34ef5be6fe1c2de), please, it has wrong naming, my bad, but contains tests for Deposit contract

Yeah,seen. @djeck1432 this task has been done. Should i go ahead with it?

**Comment by codeZe-us** [comment]
> > > Hi @codeZe-us! Before starting, could you please take a look at this [pr](https://github.com/djeck1432/spotnet/pull/69). It's still under review and I've already introduced some test cases, just so we won't repeat each other. Thanks!
> > 
> > 
> > You did not write test for [Deposit](https://github.com/djeck1432/spotnet/blob/main/src/deposit.cairo#L89C10-L89C17)
> 
> Check this [file](https://github.com/djeck1432/spotnet/pull/69/files#diff-7294b80e6dfc33c85cb9c6eba559888e08f9ebc9a1ed4ed2d34ef5be6fe1c2de), please, it has wrong naming, my bad, but contains tests for Deposit contract

@faurdent I will work on it. @djeck1432 will select what he wants

**Comment by djeck1432** [comment]
@codeZe-us Please ,text me in telegram `djeck_vorobey1` and attach this link to this issue in your message

**Comment by djeck1432** [comment]
Close this issue as duplicated

**Comment by codeZe-us** [comment]
> @codeZe-us Please ,text me in telegram `djeck_vorobey1` and attach this link to this issue in your message 

Ok

**Comment by codeZe-us** [comment]
> @codeZe-us Please ,text me in telegram `djeck_vorobey1` and attach this link to this issue in your message 

Please text me. I can't send you text due to my region/location.
CodeZe_us
