### ISSUE TITLE
Fix all pylint issues 

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#88]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. In root folder, run next command: 
```
pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301
```
4. Fix all issues from output of the running `pylint` command
Result of task done -> while creating PR, you won't have any issues in pylint and it will be marked as passed

**Comment by ikemHood** [comment]
can i take this?

**Comment by djeck1432** [comment]
one more attempt, before applying to issue, you should read guideline @ikemHood

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Python, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

### How I plan on tackling this issue
My Approach includes Pull Request (PR) includes:
- Reviewing of existing Documentation:
By thoroughly reading the current documentation, including README files, code comments, and any other relevant documentation provided in the repository.
-Identify areas that are unclear, outdated, or missing crucial information that would benefit users and developers.
- Write a well-structured template containing the needed information using the correct references.
- Note changes and define all code snippets and technical terms simply.
- fix all issues for pylint.
- Create a Pull Request (PR).
- Request for a Review.
- Make changes based on the Review of the PR

**Comment by djeck1432** [comment]
@coloredpanda Please, read guideline

**Comment by ikemHood** [comment]
🚀
